/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: KynzDgv1-NaR

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: KynzDgv1-NaR/css

import Ellipse692Icon from "./icons/PlasmicIcon__Ellipse692"; // plasmic-import: QSFcjnrXqUXs/icon
import Frame149287628Icon from "./icons/PlasmicIcon__Frame149287628"; // plasmic-import: sGxTmPtc5pPp/icon
import CalendarCalendarIcon from "./icons/PlasmicIcon__CalendarCalendar"; // plasmic-import: 955Rrjp1RWUL/icon
import ArrowChevronRightIcon from "./icons/PlasmicIcon__ArrowChevronRight"; // plasmic-import: 3QDC0LyA65OX/icon
import CommunicationBellRingIcon from "./icons/PlasmicIcon__CommunicationBellRing"; // plasmic-import: yRUitfzQMAry/icon
import EnvironmentCoffeeIcon from "./icons/PlasmicIcon__EnvironmentCoffee"; // plasmic-import: jkEfj6wFtAZc/icon
import CalendarAlarmIcon from "./icons/PlasmicIcon__CalendarAlarm"; // plasmic-import: Dj9C-pMQoICY/icon
import CalendarCalendarRemoveIcon from "./icons/PlasmicIcon__CalendarCalendarRemove"; // plasmic-import: lskjNFLUdKfb/icon
import FileCloudRemoveIcon from "./icons/PlasmicIcon__FileCloudRemove"; // plasmic-import: hGzc2xOcdZC9/icon
import MenuCloseMdIcon from "./icons/PlasmicIcon__MenuCloseMd"; // plasmic-import: ov_pm5ZDY9Dq/icon
import UserUsersGroupIcon from "./icons/PlasmicIcon__UserUsersGroup"; // plasmic-import: 8YYbEIpiqksB/icon
import FileFileDocumentIcon from "./icons/PlasmicIcon__FileFileDocument"; // plasmic-import: UkJSgGjmh3C0/icon
import VectorIcon from "./icons/PlasmicIcon__Vector"; // plasmic-import: mix-DtREsHLZ/icon
import Rectangle1556Icon from "./icons/PlasmicIcon__Rectangle1556"; // plasmic-import: eE_fHLsxz0Ec/icon
import Vector2Icon from "./icons/PlasmicIcon__Vector2"; // plasmic-import: EZENRxJYAdTV/icon
import Frame599Icon from "./icons/PlasmicIcon__Frame599"; // plasmic-import: Zv3Kgwk3PrOp/icon
import InterfaceExitIcon from "./icons/PlasmicIcon__InterfaceExit"; // plasmic-import: ZMti0_VkdAkc/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export function generateDynamicMetadata($q: any, $ctx: any) {
  return {
    openGraph: {},
    twitter: {
      card: "summary"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"div">;
  conciliumDefault?: Flex__<"div">;
  frame149287840?: Flex__<"div">;
  image3?: Flex__<"div">;
  image2?: Flex__<"div">;
  image4?: Flex__<"div">;
  frame149287627?: Flex__<"div">;
  frame149287621?: Flex__<"div">;
  image5?: Flex__<"div">;
  bottomPanel?: Flex__<"div">;
  frame149287813?: Flex__<"div">;
  выбрано3?: Flex__<"div">;
  button?: Flex__<"div">;
  iconPlaceholder?: Flex__<"div">;
  buttonText?: Flex__<"div">;
  calendar?: Flex__<"div">;
  menuItemList?: Flex__<"div">;
  menuItem?: Flex__<"div">;
  frame149287850?: Flex__<"div">;
  chevronRight?: Flex__<"div">;
  menuItem2?: Flex__<"div">;
  frame149287851?: Flex__<"div">;
  тяжелаяЛжнНеобходимостьВаЭкмо1?: Flex__<"div">;
  чквВаЭкмо1?: Flex__<"div">;
  chevronRight2?: Flex__<"div">;
  menuItem3?: Flex__<"div">;
  frame149287852?: Flex__<"div">;
  тяжелаяЛжнНеобходимостьВаЭкмо2?: Flex__<"div">;
  чквВаЭкмо2?: Flex__<"div">;
  chevronRight3?: Flex__<"div">;
  menuItem4?: Flex__<"div">;
  frame149287853?: Flex__<"div">;
  тяжелаяЛжнНеобходимостьВаЭкмо3?: Flex__<"div">;
  чквВаЭкмо3?: Flex__<"div">;
  chevronRight4?: Flex__<"div">;
  component90?: Flex__<"div">;
  frame149287854?: Flex__<"div">;
  тяжелаяЛжнНеобходимостьВаЭкмо4?: Flex__<"div">;
  чквВаЭкмо4?: Flex__<"div">;
  chevronRight5?: Flex__<"div">;
  component91?: Flex__<"div">;
  frame149287855?: Flex__<"div">;
  тяжелаяЛжнНеобходимостьВаЭкмо?: Flex__<"div">;
  чквВаЭкмо?: Flex__<"div">;
  chevronRight6?: Flex__<"div">;
  frame149287864?: Flex__<"div">;
  frame149287847?: Flex__<"div">;
  menu1?: Flex__<"div">;
  bg?: Flex__<"div">;
  lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11?: Flex__<"div">;
  rectangle9?: Flex__<"div">;
  frame1492878811?: Flex__<"div">;
  bg2?: Flex__<"div">;
  frame1492878812?: Flex__<"div">;
  title?: Flex__<"div">;
  bellRing?: Flex__<"div">;
  buttonAdd?: Flex__<"div">;
  frame149287849?: Flex__<"div">;
  rectangle5?: Flex__<"div">;
  rectangle6?: Flex__<"div">;
  menu12?: Flex__<"div">;
  bg3?: Flex__<"div">;
  frame1492878821?: Flex__<"div">;
  title2?: Flex__<"div">;
  coffee?: Flex__<"div">;
  buttonAdd2?: Flex__<"div">;
  frame149287856?: Flex__<"div">;
  rectangle7?: Flex__<"div">;
  rectangle8?: Flex__<"div">;
  frame149287848?: Flex__<"div">;
  menu13?: Flex__<"div">;
  frame149287866?: Flex__<"div">;
  alarm?: Flex__<"div">;
  buttonAdd3?: Flex__<"div">;
  frame149287857?: Flex__<"div">;
  rectangle10?: Flex__<"div">;
  rectangle11?: Flex__<"div">;
  bg4?: Flex__<"div">;
  skelet1?: Flex__<"div">;
  menu14?: Flex__<"div">;
  bg5?: Flex__<"div">;
  skelet11?: Flex__<"div">;
  frame149287867?: Flex__<"div">;
  calendarRemove?: Flex__<"div">;
  buttonAdd4?: Flex__<"div">;
  frame149287858?: Flex__<"div">;
  rectangle12?: Flex__<"div">;
  rectangle13?: Flex__<"div">;
  menu15?: Flex__<"div">;
  bg6?: Flex__<"div">;
  skelet21?: Flex__<"div">;
  frame149287868?: Flex__<"div">;
  cloudRemove?: Flex__<"div">;
  buttonAdd5?: Flex__<"div">;
  frame149287859?: Flex__<"div">;
  rectangle14?: Flex__<"div">;
  rectangle15?: Flex__<"div">;
  about?: Flex__<"div">;
  frame149287869?: Flex__<"div">;
  button2?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  closeMd?: Flex__<"div">;
  buttonText2?: Flex__<"div">;
  frame149287815?: Flex__<"div">;
  button3?: Flex__<"div">;
  usersGroup?: Flex__<"div">;
  buttonText3?: Flex__<"div">;
  calendar2?: Flex__<"div">;
  button4?: Flex__<"div">;
  uDoc?: Flex__<"div">;
  buttonText4?: Flex__<"div">;
  calendar3?: Flex__<"div">;
  header?: Flex__<"div">;
  logo?: Flex__<"div">;
  frame596?: Flex__<"a">;
  frame598?: Flex__<"div">;
  rectangle1555?: Flex__<"div">;
  button5?: Flex__<"div">;
  iconPlaceholder2?: Flex__<"div">;
  buttonText5?: Flex__<"div">;
  exit?: Flex__<"div">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"conciliumDefault"}
            data-plasmic-override={overrides.conciliumDefault}
            className={classNames(projectcss.all, sty.conciliumDefault)}
          >
            <div
              data-plasmic-name={"frame149287840"}
              data-plasmic-override={overrides.frame149287840}
              className={classNames(projectcss.all, sty.frame149287840)}
            >
              <div
                data-plasmic-name={"image3"}
                data-plasmic-override={overrides.image3}
                className={classNames(projectcss.all, sty.image3)}
              />

              <div
                data-plasmic-name={"image2"}
                data-plasmic-override={overrides.image2}
                className={classNames(projectcss.all, sty.image2)}
              />

              <div
                data-plasmic-name={"image4"}
                data-plasmic-override={overrides.image4}
                className={classNames(projectcss.all, sty.image4)}
              />
            </div>
            {false ? (
              <div
                data-plasmic-name={"frame149287627"}
                data-plasmic-override={overrides.frame149287627}
                className={classNames(projectcss.all, sty.frame149287627)}
              >
                <Ellipse692Icon
                  className={classNames(projectcss.all, sty.svg__dc0Nl)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"frame149287621"}
                  data-plasmic-override={overrides.frame149287621}
                  className={classNames(projectcss.all, sty.frame149287621)}
                >
                  <Frame149287628Icon
                    className={classNames(projectcss.all, sty.svg__abSxu)}
                    role={"img"}
                  />
                </div>
              </div>
            ) : null}
            <div
              data-plasmic-name={"image5"}
              data-plasmic-override={overrides.image5}
              className={classNames(projectcss.all, sty.image5)}
            />

            <div
              data-plasmic-name={"bottomPanel"}
              data-plasmic-override={overrides.bottomPanel}
              className={classNames(projectcss.all, sty.bottomPanel)}
            >
              <div
                data-plasmic-name={"frame149287813"}
                data-plasmic-override={overrides.frame149287813}
                className={classNames(projectcss.all, sty.frame149287813)}
              >
                <div
                  data-plasmic-name={
                    "\u0432\u044b\u0431\u0440\u0430\u043d\u043e3"
                  }
                  data-plasmic-override={overrides.выбрано3}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.выбрано3
                  )}
                >
                  {"\u0412\u044b\u0431\u0440\u0430\u043d\u043e: 1"}
                </div>
                <div
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames(projectcss.all, sty.button)}
                >
                  {false ? (
                    <div
                      data-plasmic-name={"iconPlaceholder"}
                      data-plasmic-override={overrides.iconPlaceholder}
                      className={classNames(
                        projectcss.all,
                        sty.iconPlaceholder
                      )}
                    />
                  ) : null}
                  <div
                    data-plasmic-name={"buttonText"}
                    data-plasmic-override={overrides.buttonText}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.buttonText
                    )}
                  >
                    {"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c"}
                  </div>
                  {false ? (
                    <div
                      data-plasmic-name={"calendar"}
                      data-plasmic-override={overrides.calendar}
                      className={classNames(projectcss.all, sty.calendar)}
                    >
                      <CalendarCalendarIcon
                        className={classNames(projectcss.all, sty.svg__mSxy)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"menuItemList"}
              data-plasmic-override={overrides.menuItemList}
              className={classNames(projectcss.all, sty.menuItemList)}
            >
              <div
                data-plasmic-name={"menuItem"}
                data-plasmic-override={overrides.menuItem}
                className={classNames(projectcss.all, sty.menuItem)}
              >
                <div
                  data-plasmic-name={"frame149287850"}
                  data-plasmic-override={overrides.frame149287850}
                  className={classNames(projectcss.all, sty.frame149287850)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nvTye
                    )}
                  >
                    {
                      "\u0422\u044f\u0436\u0435\u043b\u0430\u044f \u041b\u0416\u041d, \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yAssy
                    )}
                  >
                    {
                      "\u0427\u041a\u0412 + \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight"}
                  data-plasmic-override={overrides.chevronRight}
                  className={classNames(projectcss.all, sty.chevronRight)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__m9Rd1)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"menuItem2"}
                data-plasmic-override={overrides.menuItem2}
                className={classNames(projectcss.all, sty.menuItem2)}
              >
                <div
                  data-plasmic-name={"frame149287851"}
                  data-plasmic-override={overrides.frame149287851}
                  className={classNames(projectcss.all, sty.frame149287851)}
                >
                  <div
                    data-plasmic-name={
                      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1"
                    }
                    data-plasmic-override={
                      overrides.тяжелаяЛжнНеобходимостьВаЭкмо1
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.тяжелаялжннеобходимостьваэкмо1
                    )}
                  >
                    {
                      "\u041c\u043d\u043e\u0433\u043e\u0441\u043e\u0441\u0443\u0434\u0438\u0441\u0442\u0430\u044f \u043a\u043e\u0440\u043e\u043d\u0430\u0440\u043d\u0430\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u044c \u0441 \u043a\u0430\u043b\u044c\u0446\u0438\u043d\u043e\u0437\u043e\u043c"
                    }
                  </div>
                  <div
                    data-plasmic-name={
                      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1"
                    }
                    data-plasmic-override={overrides.чквВаЭкмо1}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.чквваэкмо1
                    )}
                  >
                    {
                      "\u0421\u0442\u0432\u043e\u043b \u041b\u041a\u0410: 85\u201390% \u0441\u0442\u0435\u043d\u043e\u0437"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight2"}
                  data-plasmic-override={overrides.chevronRight2}
                  className={classNames(projectcss.all, sty.chevronRight2)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__mNwOi)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"menuItem3"}
                data-plasmic-override={overrides.menuItem3}
                className={classNames(projectcss.all, sty.menuItem3)}
              >
                <div
                  data-plasmic-name={"frame149287852"}
                  data-plasmic-override={overrides.frame149287852}
                  className={classNames(projectcss.all, sty.frame149287852)}
                >
                  <div
                    data-plasmic-name={
                      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2"
                    }
                    data-plasmic-override={
                      overrides.тяжелаяЛжнНеобходимостьВаЭкмо2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.тяжелаялжннеобходимостьваэкмо2
                    )}
                  >
                    {
                      "\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0430\u043e\u0440\u0442\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0441\u0442\u0435\u043d\u043e\u0437\u0430"
                    }
                  </div>
                  <div
                    data-plasmic-name={
                      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2"
                    }
                    data-plasmic-override={overrides.чквВаЭкмо2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.чквваэкмо2
                    )}
                  >
                    {
                      "\u0422\u044f\u0436\u0435\u043b\u044b\u0439 \u0430\u043e\u0440\u0442\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u0442\u0435\u043d\u043e\u0437"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight3"}
                  data-plasmic-override={overrides.chevronRight3}
                  className={classNames(projectcss.all, sty.chevronRight3)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__oSeBe)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"menuItem4"}
                data-plasmic-override={overrides.menuItem4}
                className={classNames(projectcss.all, sty.menuItem4)}
              >
                <div
                  data-plasmic-name={"frame149287853"}
                  data-plasmic-override={overrides.frame149287853}
                  className={classNames(projectcss.all, sty.frame149287853)}
                >
                  <div
                    data-plasmic-name={
                      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3"
                    }
                    data-plasmic-override={
                      overrides.тяжелаяЛжнНеобходимостьВаЭкмо3
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.тяжелаялжннеобходимостьваэкмо3
                    )}
                  >
                    {
                      "\u0413\u0438\u043f\u0435\u0440\u044d\u0445\u043e\u0433\u0435\u043d\u043d\u044b\u0435 \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b \u0432 \u041d\u041f\u0412/\u043f\u0440\u0430\u0432\u043e\u043c \u043f\u0440\u0435\u0434\u0441\u0435\u0440\u0434\u0438\u0438 (\u0442\u0440\u043e\u043c\u0431\u044b? \u043a\u0430\u043b\u044c\u0446\u0438\u043d\u043e\u0437?)"
                    }
                  </div>
                  <div
                    data-plasmic-name={
                      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3"
                    }
                    data-plasmic-override={overrides.чквВаЭкмо3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.чквваэкмо3
                    )}
                  >
                    {
                      "\u041f\u0440\u0438\u0440\u043e\u0434\u0430 \u043f\u043e\u0434 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u043c"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight4"}
                  data-plasmic-override={overrides.chevronRight4}
                  className={classNames(projectcss.all, sty.chevronRight4)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__k1Wer)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"component90"}
                data-plasmic-override={overrides.component90}
                className={classNames(projectcss.all, sty.component90)}
              >
                <div
                  data-plasmic-name={"frame149287854"}
                  data-plasmic-override={overrides.frame149287854}
                  className={classNames(projectcss.all, sty.frame149287854)}
                >
                  <div
                    data-plasmic-name={
                      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4"
                    }
                    data-plasmic-override={
                      overrides.тяжелаяЛжнНеобходимостьВаЭкмо4
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.тяжелаялжннеобходимостьваэкмо4
                    )}
                  >
                    {
                      "\u0410\u0440\u0438\u0442\u043c\u0438\u0438 (\u0416\u042d\u0421, \u0424\u041f) \u00a0"
                    }
                  </div>
                  <div
                    data-plasmic-name={
                      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4"
                    }
                    data-plasmic-override={overrides.чквВаЭкмо4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.чквваэкмо4
                    )}
                  >
                    {
                      "\u0421\u0442\u0435\u043d\u043e\u0437\u044b 80\u201395% + \u0440\u0435\u0437\u043a\u043e \u0441\u043d\u0438\u0436\u0435\u043d\u043d\u0430\u044f \u0424\u0412"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight5"}
                  data-plasmic-override={overrides.chevronRight5}
                  className={classNames(projectcss.all, sty.chevronRight5)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__dv07G)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"component91"}
                data-plasmic-override={overrides.component91}
                className={classNames(projectcss.all, sty.component91)}
              >
                <div
                  data-plasmic-name={"frame149287855"}
                  data-plasmic-override={overrides.frame149287855}
                  className={classNames(projectcss.all, sty.frame149287855)}
                >
                  <div
                    data-plasmic-name={
                      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e"
                    }
                    data-plasmic-override={
                      overrides.тяжелаяЛжнНеобходимостьВаЭкмо
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.тяжелаялжннеобходимостьваэкмо
                    )}
                  >
                    {
                      "\u041d\u0438\u0437\u043a\u0438\u0439 \u0434\u0438\u0443\u0440\u0435\u0437, \u0440\u0438\u0441\u043a \u043f\u043e\u0447\u0435\u0447\u043d\u043e\u0439 \u0434\u0438\u0441\u0444\u0443\u043d\u043a\u0446\u0438\u0438 \u00a0"
                    }
                  </div>
                  <div
                    data-plasmic-name={
                      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e"
                    }
                    data-plasmic-override={overrides.чквВаЭкмо}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.чквваэкмо
                    )}
                  >
                    {
                      "\u041b\u0416\u041d + \u0432\u044b\u0441\u043e\u043a\u0438\u0435 \u0434\u043e\u0437\u044b \u0432\u0430\u0437\u043e\u043f\u0440\u0435\u0441\u0441\u043e\u0440\u043e\u0432 (NA 1,1; A 0,07)"
                    }
                  </div>
                </div>
                <div
                  data-plasmic-name={"chevronRight6"}
                  data-plasmic-override={overrides.chevronRight6}
                  className={classNames(projectcss.all, sty.chevronRight6)}
                >
                  <ArrowChevronRightIcon
                    className={classNames(projectcss.all, sty.svg__wOfc)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"frame149287864"}
              data-plasmic-override={overrides.frame149287864}
              className={classNames(projectcss.all, sty.frame149287864)}
            >
              <div
                data-plasmic-name={"frame149287847"}
                data-plasmic-override={overrides.frame149287847}
                className={classNames(projectcss.all, sty.frame149287847)}
              >
                <div
                  data-plasmic-name={"menu1"}
                  data-plasmic-override={overrides.menu1}
                  className={classNames(projectcss.all, sty.menu1)}
                >
                  <div
                    data-plasmic-name={"bg"}
                    data-plasmic-override={overrides.bg}
                    className={classNames(projectcss.all, sty.bg)}
                  >
                    {false ? (
                      <div
                        data-plasmic-name={
                          "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11"
                        }
                        data-plasmic-override={
                          overrides.lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11
                        }
                        className={classNames(
                          projectcss.all,
                          sty.lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11
                        )}
                      />
                    ) : null}
                    {false ? (
                      <div
                        data-plasmic-name={"rectangle9"}
                        data-plasmic-override={overrides.rectangle9}
                        className={classNames(projectcss.all, sty.rectangle9)}
                      />
                    ) : null}
                    <div
                      data-plasmic-name={"frame1492878811"}
                      data-plasmic-override={overrides.frame1492878811}
                      className={classNames(
                        projectcss.all,
                        sty.frame1492878811
                      )}
                    />
                  </div>
                  <div
                    data-plasmic-name={"bg2"}
                    data-plasmic-override={overrides.bg2}
                    className={classNames(projectcss.all, sty.bg2)}
                  >
                    <div
                      data-plasmic-name={"frame1492878812"}
                      data-plasmic-override={overrides.frame1492878812}
                      className={classNames(
                        projectcss.all,
                        sty.frame1492878812
                      )}
                    />
                  </div>
                  <div
                    data-plasmic-name={"title"}
                    data-plasmic-override={overrides.title}
                    className={classNames(projectcss.all, sty.title)}
                  >
                    <div
                      data-plasmic-name={"bellRing"}
                      data-plasmic-override={overrides.bellRing}
                      className={classNames(projectcss.all, sty.bellRing)}
                    >
                      <CommunicationBellRingIcon
                        className={classNames(projectcss.all, sty.svg__eaAyI)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__itbFi
                      )}
                    >
                      {
                        "\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u0438"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"buttonAdd"}
                    data-plasmic-override={overrides.buttonAdd}
                    className={classNames(projectcss.all, sty.buttonAdd)}
                  >
                    <div
                      data-plasmic-name={"frame149287849"}
                      data-plasmic-override={overrides.frame149287849}
                      className={classNames(projectcss.all, sty.frame149287849)}
                    >
                      <div
                        data-plasmic-name={"rectangle5"}
                        data-plasmic-override={overrides.rectangle5}
                        className={classNames(projectcss.all, sty.rectangle5)}
                      />

                      <div
                        data-plasmic-name={"rectangle6"}
                        data-plasmic-override={overrides.rectangle6}
                        className={classNames(projectcss.all, sty.rectangle6)}
                      />
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"menu12"}
                  data-plasmic-override={overrides.menu12}
                  className={classNames(projectcss.all, sty.menu12)}
                >
                  <div
                    data-plasmic-name={"bg3"}
                    data-plasmic-override={overrides.bg3}
                    className={classNames(projectcss.all, sty.bg3)}
                  >
                    <div
                      data-plasmic-name={"frame1492878821"}
                      data-plasmic-override={overrides.frame1492878821}
                      className={classNames(
                        projectcss.all,
                        sty.frame1492878821
                      )}
                    />
                  </div>
                  <div
                    data-plasmic-name={"title2"}
                    data-plasmic-override={overrides.title2}
                    className={classNames(projectcss.all, sty.title2)}
                  >
                    <div
                      data-plasmic-name={"coffee"}
                      data-plasmic-override={overrides.coffee}
                      className={classNames(projectcss.all, sty.coffee)}
                    >
                      <EnvironmentCoffeeIcon
                        className={classNames(projectcss.all, sty.svg__lNbc)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__blD7Z
                      )}
                    >
                      {
                        "\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u044b\u0435"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"buttonAdd2"}
                    data-plasmic-override={overrides.buttonAdd2}
                    className={classNames(projectcss.all, sty.buttonAdd2)}
                  >
                    <div
                      data-plasmic-name={"frame149287856"}
                      data-plasmic-override={overrides.frame149287856}
                      className={classNames(projectcss.all, sty.frame149287856)}
                    >
                      <div
                        data-plasmic-name={"rectangle7"}
                        data-plasmic-override={overrides.rectangle7}
                        className={classNames(projectcss.all, sty.rectangle7)}
                      />

                      <div
                        data-plasmic-name={"rectangle8"}
                        data-plasmic-override={overrides.rectangle8}
                        className={classNames(projectcss.all, sty.rectangle8)}
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"frame149287848"}
                data-plasmic-override={overrides.frame149287848}
                className={classNames(projectcss.all, sty.frame149287848)}
              >
                <div
                  data-plasmic-name={"menu13"}
                  data-plasmic-override={overrides.menu13}
                  className={classNames(projectcss.all, sty.menu13)}
                >
                  <div
                    data-plasmic-name={"frame149287866"}
                    data-plasmic-override={overrides.frame149287866}
                    className={classNames(projectcss.all, sty.frame149287866)}
                  >
                    <div
                      data-plasmic-name={"alarm"}
                      data-plasmic-override={overrides.alarm}
                      className={classNames(projectcss.all, sty.alarm)}
                    >
                      <CalendarAlarmIcon
                        className={classNames(projectcss.all, sty.svg__kexXm)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aCq4F
                      )}
                    >
                      {
                        "\u0410\u043d\u0430\u0442\u043e\u043c\u0438\u0447\u0435\u0441\u043a\u0438\u0435"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"buttonAdd3"}
                    data-plasmic-override={overrides.buttonAdd3}
                    className={classNames(projectcss.all, sty.buttonAdd3)}
                  >
                    <div
                      data-plasmic-name={"frame149287857"}
                      data-plasmic-override={overrides.frame149287857}
                      className={classNames(projectcss.all, sty.frame149287857)}
                    >
                      <div
                        data-plasmic-name={"rectangle10"}
                        data-plasmic-override={overrides.rectangle10}
                        className={classNames(projectcss.all, sty.rectangle10)}
                      />

                      <div
                        data-plasmic-name={"rectangle11"}
                        data-plasmic-override={overrides.rectangle11}
                        className={classNames(projectcss.all, sty.rectangle11)}
                      />
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"bg4"}
                    data-plasmic-override={overrides.bg4}
                    className={classNames(projectcss.all, sty.bg4)}
                  >
                    <div
                      data-plasmic-name={"skelet1"}
                      data-plasmic-override={overrides.skelet1}
                      className={classNames(projectcss.all, sty.skelet1)}
                    />
                  </div>
                </div>
                <div
                  data-plasmic-name={"menu14"}
                  data-plasmic-override={overrides.menu14}
                  className={classNames(projectcss.all, sty.menu14)}
                >
                  <div
                    data-plasmic-name={"bg5"}
                    data-plasmic-override={overrides.bg5}
                    className={classNames(projectcss.all, sty.bg5)}
                  >
                    <div
                      data-plasmic-name={"skelet11"}
                      data-plasmic-override={overrides.skelet11}
                      className={classNames(projectcss.all, sty.skelet11)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame149287867"}
                    data-plasmic-override={overrides.frame149287867}
                    className={classNames(projectcss.all, sty.frame149287867)}
                  >
                    <div
                      data-plasmic-name={"calendarRemove"}
                      data-plasmic-override={overrides.calendarRemove}
                      className={classNames(projectcss.all, sty.calendarRemove)}
                    >
                      <CalendarCalendarRemoveIcon
                        className={classNames(projectcss.all, sty.svg__oG52H)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gAPb
                      )}
                    >
                      {
                        "\u0424\u0443\u043d\u043a\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"buttonAdd4"}
                    data-plasmic-override={overrides.buttonAdd4}
                    className={classNames(projectcss.all, sty.buttonAdd4)}
                  >
                    <div
                      data-plasmic-name={"frame149287858"}
                      data-plasmic-override={overrides.frame149287858}
                      className={classNames(projectcss.all, sty.frame149287858)}
                    >
                      <div
                        data-plasmic-name={"rectangle12"}
                        data-plasmic-override={overrides.rectangle12}
                        className={classNames(projectcss.all, sty.rectangle12)}
                      />

                      <div
                        data-plasmic-name={"rectangle13"}
                        data-plasmic-override={overrides.rectangle13}
                        className={classNames(projectcss.all, sty.rectangle13)}
                      />
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"menu15"}
                  data-plasmic-override={overrides.menu15}
                  className={classNames(projectcss.all, sty.menu15)}
                >
                  <div
                    data-plasmic-name={"bg6"}
                    data-plasmic-override={overrides.bg6}
                    className={classNames(projectcss.all, sty.bg6)}
                  >
                    <div
                      data-plasmic-name={"skelet21"}
                      data-plasmic-override={overrides.skelet21}
                      className={classNames(projectcss.all, sty.skelet21)}
                    />
                  </div>
                  <div
                    data-plasmic-name={"frame149287868"}
                    data-plasmic-override={overrides.frame149287868}
                    className={classNames(projectcss.all, sty.frame149287868)}
                  >
                    <div
                      data-plasmic-name={"cloudRemove"}
                      data-plasmic-override={overrides.cloudRemove}
                      className={classNames(projectcss.all, sty.cloudRemove)}
                    >
                      <FileCloudRemoveIcon
                        className={classNames(projectcss.all, sty.svg___5WvJu)}
                        role={"img"}
                      />
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fJa04
                      )}
                    >
                      {
                        "\u042d\u043d\u0434\u043e\u0441\u043a\u043e\u043f\u0438\u0447\u0435\u0441\u043a\u0438\u0435"
                      }
                    </div>
                  </div>
                  <div
                    data-plasmic-name={"buttonAdd5"}
                    data-plasmic-override={overrides.buttonAdd5}
                    className={classNames(projectcss.all, sty.buttonAdd5)}
                  >
                    <div
                      data-plasmic-name={"frame149287859"}
                      data-plasmic-override={overrides.frame149287859}
                      className={classNames(projectcss.all, sty.frame149287859)}
                    >
                      <div
                        data-plasmic-name={"rectangle14"}
                        data-plasmic-override={overrides.rectangle14}
                        className={classNames(projectcss.all, sty.rectangle14)}
                      />

                      <div
                        data-plasmic-name={"rectangle15"}
                        data-plasmic-override={overrides.rectangle15}
                        className={classNames(projectcss.all, sty.rectangle15)}
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"about"}
              data-plasmic-override={overrides.about}
              className={classNames(projectcss.all, sty.about)}
            >
              <div
                data-plasmic-name={"frame149287869"}
                data-plasmic-override={overrides.frame149287869}
                className={classNames(projectcss.all, sty.frame149287869)}
              >
                <div
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames(projectcss.all, sty.button2)}
                >
                  <div
                    data-plasmic-name={"freeBox"}
                    data-plasmic-override={overrides.freeBox}
                    className={classNames(projectcss.all, sty.freeBox)}
                  >
                    <div
                      data-plasmic-name={"closeMd"}
                      data-plasmic-override={overrides.closeMd}
                      className={classNames(projectcss.all, sty.closeMd)}
                    >
                      <MenuCloseMdIcon
                        className={classNames(projectcss.all, sty.svg__kv74D)}
                        role={"img"}
                      />
                    </div>
                  </div>
                </div>
                <div
                  data-plasmic-name={"buttonText2"}
                  data-plasmic-override={overrides.buttonText2}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.buttonText2
                  )}
                >
                  {"8978117000081"}
                </div>
              </div>
              <div
                data-plasmic-name={"frame149287815"}
                data-plasmic-override={overrides.frame149287815}
                className={classNames(projectcss.all, sty.frame149287815)}
              >
                <div
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  className={classNames(projectcss.all, sty.button3)}
                >
                  <div
                    data-plasmic-name={"usersGroup"}
                    data-plasmic-override={overrides.usersGroup}
                    className={classNames(projectcss.all, sty.usersGroup)}
                  >
                    <UserUsersGroupIcon
                      className={classNames(projectcss.all, sty.svg__dx1S)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"buttonText3"}
                    data-plasmic-override={overrides.buttonText3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.buttonText3
                    )}
                  >
                    {
                      "\u0420\u0435\u0436\u0438\u043c \u043a\u043e\u043d\u0441\u0438\u043b\u0438\u0443\u043c\u0430"
                    }
                  </div>
                  {false ? (
                    <div
                      data-plasmic-name={"calendar2"}
                      data-plasmic-override={overrides.calendar2}
                      className={classNames(projectcss.all, sty.calendar2)}
                    >
                      <CalendarCalendarIcon
                        className={classNames(projectcss.all, sty.svg__hyHy)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                </div>
                <div
                  data-plasmic-name={"button4"}
                  data-plasmic-override={overrides.button4}
                  className={classNames(projectcss.all, sty.button4)}
                >
                  <div
                    data-plasmic-name={"uDoc"}
                    data-plasmic-override={overrides.uDoc}
                    className={classNames(projectcss.all, sty.uDoc)}
                  >
                    <FileFileDocumentIcon
                      className={classNames(projectcss.all, sty.svg__d0Fto)}
                      role={"img"}
                    />

                    <VectorIcon
                      className={classNames(projectcss.all, sty.svg__iqsqc)}
                      role={"img"}
                    />

                    <VectorIcon
                      className={classNames(projectcss.all, sty.svg__aCs58)}
                      role={"img"}
                    />
                  </div>
                  <div
                    data-plasmic-name={"buttonText4"}
                    data-plasmic-override={overrides.buttonText4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.buttonText4
                    )}
                  >
                    {
                      "\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u044d\u043f\u0438\u043a\u0440\u0438\u0437"
                    }
                  </div>
                  {false ? (
                    <div
                      data-plasmic-name={"calendar3"}
                      data-plasmic-override={overrides.calendar3}
                      className={classNames(projectcss.all, sty.calendar3)}
                    >
                      <CalendarCalendarIcon
                        className={classNames(projectcss.all, sty.svg__bbRqU)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(projectcss.all, sty.header)}
            >
              <div
                data-plasmic-name={"logo"}
                data-plasmic-override={overrides.logo}
                className={classNames(projectcss.all, sty.logo)}
              >
                <PlasmicLink__
                  data-plasmic-name={"frame596"}
                  data-plasmic-override={overrides.frame596}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.frame596
                  )}
                  href={`/`}
                  platform={"react"}
                >
                  <div
                    data-plasmic-name={"frame598"}
                    data-plasmic-override={overrides.frame598}
                    className={classNames(projectcss.all, sty.frame598)}
                  >
                    <Rectangle1556Icon
                      className={classNames(projectcss.all, sty.svg___5HuFs)}
                      role={"img"}
                    />

                    <Vector2Icon
                      className={classNames(projectcss.all, sty.svg__rcKoK)}
                      role={"img"}
                    />

                    <div
                      data-plasmic-name={"rectangle1555"}
                      data-plasmic-override={overrides.rectangle1555}
                      className={classNames(projectcss.all, sty.rectangle1555)}
                    />
                  </div>
                  <Frame599Icon
                    className={classNames(projectcss.all, sty.svg__pOg9J)}
                    role={"img"}
                  />
                </PlasmicLink__>
              </div>
              <div
                data-plasmic-name={"button5"}
                data-plasmic-override={overrides.button5}
                className={classNames(projectcss.all, sty.button5)}
              >
                {false ? (
                  <div
                    data-plasmic-name={"iconPlaceholder2"}
                    data-plasmic-override={overrides.iconPlaceholder2}
                    className={classNames(projectcss.all, sty.iconPlaceholder2)}
                  />
                ) : null}
                <div
                  data-plasmic-name={"buttonText5"}
                  data-plasmic-override={overrides.buttonText5}
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.buttonText5
                  )}
                >
                  {"\u0412\u044b\u0439\u0442\u0438"}
                </div>
                <div
                  data-plasmic-name={"exit"}
                  data-plasmic-override={overrides.exit}
                  className={classNames(projectcss.all, sty.exit)}
                >
                  <InterfaceExitIcon
                    className={classNames(projectcss.all, sty.svg__kzIYs)}
                    role={"img"}
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "conciliumDefault",
    "frame149287840",
    "image3",
    "image2",
    "image4",
    "frame149287627",
    "frame149287621",
    "image5",
    "bottomPanel",
    "frame149287813",
    "\u0432\u044b\u0431\u0440\u0430\u043d\u043e3",
    "button",
    "iconPlaceholder",
    "buttonText",
    "calendar",
    "menuItemList",
    "menuItem",
    "frame149287850",
    "chevronRight",
    "menuItem2",
    "frame149287851",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1",
    "chevronRight2",
    "menuItem3",
    "frame149287852",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2",
    "chevronRight3",
    "menuItem4",
    "frame149287853",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3",
    "chevronRight4",
    "component90",
    "frame149287854",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4",
    "chevronRight5",
    "component91",
    "frame149287855",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e",
    "chevronRight6",
    "frame149287864",
    "frame149287847",
    "menu1",
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811",
    "bg2",
    "frame1492878812",
    "title",
    "bellRing",
    "buttonAdd",
    "frame149287849",
    "rectangle5",
    "rectangle6",
    "menu12",
    "bg3",
    "frame1492878821",
    "title2",
    "coffee",
    "buttonAdd2",
    "frame149287856",
    "rectangle7",
    "rectangle8",
    "frame149287848",
    "menu13",
    "frame149287866",
    "alarm",
    "buttonAdd3",
    "frame149287857",
    "rectangle10",
    "rectangle11",
    "bg4",
    "skelet1",
    "menu14",
    "bg5",
    "skelet11",
    "frame149287867",
    "calendarRemove",
    "buttonAdd4",
    "frame149287858",
    "rectangle12",
    "rectangle13",
    "menu15",
    "bg6",
    "skelet21",
    "frame149287868",
    "cloudRemove",
    "buttonAdd5",
    "frame149287859",
    "rectangle14",
    "rectangle15",
    "about",
    "frame149287869",
    "button2",
    "freeBox",
    "closeMd",
    "buttonText2",
    "frame149287815",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3",
    "header",
    "logo",
    "frame596",
    "frame598",
    "rectangle1555",
    "button5",
    "iconPlaceholder2",
    "buttonText5",
    "exit"
  ],
  conciliumDefault: [
    "conciliumDefault",
    "frame149287840",
    "image3",
    "image2",
    "image4",
    "frame149287627",
    "frame149287621",
    "image5",
    "bottomPanel",
    "frame149287813",
    "\u0432\u044b\u0431\u0440\u0430\u043d\u043e3",
    "button",
    "iconPlaceholder",
    "buttonText",
    "calendar",
    "menuItemList",
    "menuItem",
    "frame149287850",
    "chevronRight",
    "menuItem2",
    "frame149287851",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1",
    "chevronRight2",
    "menuItem3",
    "frame149287852",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2",
    "chevronRight3",
    "menuItem4",
    "frame149287853",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3",
    "chevronRight4",
    "component90",
    "frame149287854",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4",
    "chevronRight5",
    "component91",
    "frame149287855",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e",
    "chevronRight6",
    "frame149287864",
    "frame149287847",
    "menu1",
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811",
    "bg2",
    "frame1492878812",
    "title",
    "bellRing",
    "buttonAdd",
    "frame149287849",
    "rectangle5",
    "rectangle6",
    "menu12",
    "bg3",
    "frame1492878821",
    "title2",
    "coffee",
    "buttonAdd2",
    "frame149287856",
    "rectangle7",
    "rectangle8",
    "frame149287848",
    "menu13",
    "frame149287866",
    "alarm",
    "buttonAdd3",
    "frame149287857",
    "rectangle10",
    "rectangle11",
    "bg4",
    "skelet1",
    "menu14",
    "bg5",
    "skelet11",
    "frame149287867",
    "calendarRemove",
    "buttonAdd4",
    "frame149287858",
    "rectangle12",
    "rectangle13",
    "menu15",
    "bg6",
    "skelet21",
    "frame149287868",
    "cloudRemove",
    "buttonAdd5",
    "frame149287859",
    "rectangle14",
    "rectangle15",
    "about",
    "frame149287869",
    "button2",
    "freeBox",
    "closeMd",
    "buttonText2",
    "frame149287815",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3",
    "header",
    "logo",
    "frame596",
    "frame598",
    "rectangle1555",
    "button5",
    "iconPlaceholder2",
    "buttonText5",
    "exit"
  ],
  frame149287840: ["frame149287840", "image3", "image2", "image4"],
  image3: ["image3"],
  image2: ["image2"],
  image4: ["image4"],
  frame149287627: ["frame149287627", "frame149287621"],
  frame149287621: ["frame149287621"],
  image5: ["image5"],
  bottomPanel: [
    "bottomPanel",
    "frame149287813",
    "\u0432\u044b\u0431\u0440\u0430\u043d\u043e3",
    "button",
    "iconPlaceholder",
    "buttonText",
    "calendar"
  ],
  frame149287813: [
    "frame149287813",
    "\u0432\u044b\u0431\u0440\u0430\u043d\u043e3",
    "button",
    "iconPlaceholder",
    "buttonText",
    "calendar"
  ],
  выбрано3: ["\u0432\u044b\u0431\u0440\u0430\u043d\u043e3"],
  button: ["button", "iconPlaceholder", "buttonText", "calendar"],
  iconPlaceholder: ["iconPlaceholder"],
  buttonText: ["buttonText"],
  calendar: ["calendar"],
  menuItemList: [
    "menuItemList",
    "menuItem",
    "frame149287850",
    "chevronRight",
    "menuItem2",
    "frame149287851",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1",
    "chevronRight2",
    "menuItem3",
    "frame149287852",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2",
    "chevronRight3",
    "menuItem4",
    "frame149287853",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3",
    "chevronRight4",
    "component90",
    "frame149287854",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4",
    "chevronRight5",
    "component91",
    "frame149287855",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e",
    "chevronRight6"
  ],
  menuItem: ["menuItem", "frame149287850", "chevronRight"],
  frame149287850: ["frame149287850"],
  chevronRight: ["chevronRight"],
  menuItem2: [
    "menuItem2",
    "frame149287851",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1",
    "chevronRight2"
  ],
  frame149287851: [
    "frame149287851",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1"
  ],
  тяжелаяЛжнНеобходимостьВаЭкмо1: [
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1"
  ],
  чквВаЭкмо1: ["\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1"],
  chevronRight2: ["chevronRight2"],
  menuItem3: [
    "menuItem3",
    "frame149287852",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2",
    "chevronRight3"
  ],
  frame149287852: [
    "frame149287852",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2"
  ],
  тяжелаяЛжнНеобходимостьВаЭкмо2: [
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2"
  ],
  чквВаЭкмо2: ["\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2"],
  chevronRight3: ["chevronRight3"],
  menuItem4: [
    "menuItem4",
    "frame149287853",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3",
    "chevronRight4"
  ],
  frame149287853: [
    "frame149287853",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3"
  ],
  тяжелаяЛжнНеобходимостьВаЭкмо3: [
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3"
  ],
  чквВаЭкмо3: ["\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3"],
  chevronRight4: ["chevronRight4"],
  component90: [
    "component90",
    "frame149287854",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4",
    "chevronRight5"
  ],
  frame149287854: [
    "frame149287854",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4"
  ],
  тяжелаяЛжнНеобходимостьВаЭкмо4: [
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4"
  ],
  чквВаЭкмо4: ["\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4"],
  chevronRight5: ["chevronRight5"],
  component91: [
    "component91",
    "frame149287855",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e",
    "chevronRight6"
  ],
  frame149287855: [
    "frame149287855",
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e",
    "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e"
  ],
  тяжелаяЛжнНеобходимостьВаЭкмо: [
    "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e"
  ],
  чквВаЭкмо: ["\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e"],
  chevronRight6: ["chevronRight6"],
  frame149287864: [
    "frame149287864",
    "frame149287847",
    "menu1",
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811",
    "bg2",
    "frame1492878812",
    "title",
    "bellRing",
    "buttonAdd",
    "frame149287849",
    "rectangle5",
    "rectangle6",
    "menu12",
    "bg3",
    "frame1492878821",
    "title2",
    "coffee",
    "buttonAdd2",
    "frame149287856",
    "rectangle7",
    "rectangle8",
    "frame149287848",
    "menu13",
    "frame149287866",
    "alarm",
    "buttonAdd3",
    "frame149287857",
    "rectangle10",
    "rectangle11",
    "bg4",
    "skelet1",
    "menu14",
    "bg5",
    "skelet11",
    "frame149287867",
    "calendarRemove",
    "buttonAdd4",
    "frame149287858",
    "rectangle12",
    "rectangle13",
    "menu15",
    "bg6",
    "skelet21",
    "frame149287868",
    "cloudRemove",
    "buttonAdd5",
    "frame149287859",
    "rectangle14",
    "rectangle15"
  ],
  frame149287847: [
    "frame149287847",
    "menu1",
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811",
    "bg2",
    "frame1492878812",
    "title",
    "bellRing",
    "buttonAdd",
    "frame149287849",
    "rectangle5",
    "rectangle6",
    "menu12",
    "bg3",
    "frame1492878821",
    "title2",
    "coffee",
    "buttonAdd2",
    "frame149287856",
    "rectangle7",
    "rectangle8"
  ],
  menu1: [
    "menu1",
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811",
    "bg2",
    "frame1492878812",
    "title",
    "bellRing",
    "buttonAdd",
    "frame149287849",
    "rectangle5",
    "rectangle6"
  ],
  bg: [
    "bg",
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11",
    "rectangle9",
    "frame1492878811"
  ],
  lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11: [
    "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11"
  ],
  rectangle9: ["rectangle9"],
  frame1492878811: ["frame1492878811"],
  bg2: ["bg2", "frame1492878812"],
  frame1492878812: ["frame1492878812"],
  title: ["title", "bellRing"],
  bellRing: ["bellRing"],
  buttonAdd: ["buttonAdd", "frame149287849", "rectangle5", "rectangle6"],
  frame149287849: ["frame149287849", "rectangle5", "rectangle6"],
  rectangle5: ["rectangle5"],
  rectangle6: ["rectangle6"],
  menu12: [
    "menu12",
    "bg3",
    "frame1492878821",
    "title2",
    "coffee",
    "buttonAdd2",
    "frame149287856",
    "rectangle7",
    "rectangle8"
  ],
  bg3: ["bg3", "frame1492878821"],
  frame1492878821: ["frame1492878821"],
  title2: ["title2", "coffee"],
  coffee: ["coffee"],
  buttonAdd2: ["buttonAdd2", "frame149287856", "rectangle7", "rectangle8"],
  frame149287856: ["frame149287856", "rectangle7", "rectangle8"],
  rectangle7: ["rectangle7"],
  rectangle8: ["rectangle8"],
  frame149287848: [
    "frame149287848",
    "menu13",
    "frame149287866",
    "alarm",
    "buttonAdd3",
    "frame149287857",
    "rectangle10",
    "rectangle11",
    "bg4",
    "skelet1",
    "menu14",
    "bg5",
    "skelet11",
    "frame149287867",
    "calendarRemove",
    "buttonAdd4",
    "frame149287858",
    "rectangle12",
    "rectangle13",
    "menu15",
    "bg6",
    "skelet21",
    "frame149287868",
    "cloudRemove",
    "buttonAdd5",
    "frame149287859",
    "rectangle14",
    "rectangle15"
  ],
  menu13: [
    "menu13",
    "frame149287866",
    "alarm",
    "buttonAdd3",
    "frame149287857",
    "rectangle10",
    "rectangle11",
    "bg4",
    "skelet1"
  ],
  frame149287866: ["frame149287866", "alarm"],
  alarm: ["alarm"],
  buttonAdd3: ["buttonAdd3", "frame149287857", "rectangle10", "rectangle11"],
  frame149287857: ["frame149287857", "rectangle10", "rectangle11"],
  rectangle10: ["rectangle10"],
  rectangle11: ["rectangle11"],
  bg4: ["bg4", "skelet1"],
  skelet1: ["skelet1"],
  menu14: [
    "menu14",
    "bg5",
    "skelet11",
    "frame149287867",
    "calendarRemove",
    "buttonAdd4",
    "frame149287858",
    "rectangle12",
    "rectangle13"
  ],
  bg5: ["bg5", "skelet11"],
  skelet11: ["skelet11"],
  frame149287867: ["frame149287867", "calendarRemove"],
  calendarRemove: ["calendarRemove"],
  buttonAdd4: ["buttonAdd4", "frame149287858", "rectangle12", "rectangle13"],
  frame149287858: ["frame149287858", "rectangle12", "rectangle13"],
  rectangle12: ["rectangle12"],
  rectangle13: ["rectangle13"],
  menu15: [
    "menu15",
    "bg6",
    "skelet21",
    "frame149287868",
    "cloudRemove",
    "buttonAdd5",
    "frame149287859",
    "rectangle14",
    "rectangle15"
  ],
  bg6: ["bg6", "skelet21"],
  skelet21: ["skelet21"],
  frame149287868: ["frame149287868", "cloudRemove"],
  cloudRemove: ["cloudRemove"],
  buttonAdd5: ["buttonAdd5", "frame149287859", "rectangle14", "rectangle15"],
  frame149287859: ["frame149287859", "rectangle14", "rectangle15"],
  rectangle14: ["rectangle14"],
  rectangle15: ["rectangle15"],
  about: [
    "about",
    "frame149287869",
    "button2",
    "freeBox",
    "closeMd",
    "buttonText2",
    "frame149287815",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3"
  ],
  frame149287869: [
    "frame149287869",
    "button2",
    "freeBox",
    "closeMd",
    "buttonText2"
  ],
  button2: ["button2", "freeBox", "closeMd"],
  freeBox: ["freeBox", "closeMd"],
  closeMd: ["closeMd"],
  buttonText2: ["buttonText2"],
  frame149287815: [
    "frame149287815",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3"
  ],
  button3: ["button3", "usersGroup", "buttonText3", "calendar2"],
  usersGroup: ["usersGroup"],
  buttonText3: ["buttonText3"],
  calendar2: ["calendar2"],
  button4: ["button4", "uDoc", "buttonText4", "calendar3"],
  uDoc: ["uDoc"],
  buttonText4: ["buttonText4"],
  calendar3: ["calendar3"],
  header: [
    "header",
    "logo",
    "frame596",
    "frame598",
    "rectangle1555",
    "button5",
    "iconPlaceholder2",
    "buttonText5",
    "exit"
  ],
  logo: ["logo", "frame596", "frame598", "rectangle1555"],
  frame596: ["frame596", "frame598", "rectangle1555"],
  frame598: ["frame598", "rectangle1555"],
  rectangle1555: ["rectangle1555"],
  button5: ["button5", "iconPlaceholder2", "buttonText5", "exit"],
  iconPlaceholder2: ["iconPlaceholder2"],
  buttonText5: ["buttonText5"],
  exit: ["exit"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  conciliumDefault: "div";
  frame149287840: "div";
  image3: "div";
  image2: "div";
  image4: "div";
  frame149287627: "div";
  frame149287621: "div";
  image5: "div";
  bottomPanel: "div";
  frame149287813: "div";
  выбрано3: "div";
  button: "div";
  iconPlaceholder: "div";
  buttonText: "div";
  calendar: "div";
  menuItemList: "div";
  menuItem: "div";
  frame149287850: "div";
  chevronRight: "div";
  menuItem2: "div";
  frame149287851: "div";
  тяжелаяЛжнНеобходимостьВаЭкмо1: "div";
  чквВаЭкмо1: "div";
  chevronRight2: "div";
  menuItem3: "div";
  frame149287852: "div";
  тяжелаяЛжнНеобходимостьВаЭкмо2: "div";
  чквВаЭкмо2: "div";
  chevronRight3: "div";
  menuItem4: "div";
  frame149287853: "div";
  тяжелаяЛжнНеобходимостьВаЭкмо3: "div";
  чквВаЭкмо3: "div";
  chevronRight4: "div";
  component90: "div";
  frame149287854: "div";
  тяжелаяЛжнНеобходимостьВаЭкмо4: "div";
  чквВаЭкмо4: "div";
  chevronRight5: "div";
  component91: "div";
  frame149287855: "div";
  тяжелаяЛжнНеобходимостьВаЭкмо: "div";
  чквВаЭкмо: "div";
  chevronRight6: "div";
  frame149287864: "div";
  frame149287847: "div";
  menu1: "div";
  bg: "div";
  lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11: "div";
  rectangle9: "div";
  frame1492878811: "div";
  bg2: "div";
  frame1492878812: "div";
  title: "div";
  bellRing: "div";
  buttonAdd: "div";
  frame149287849: "div";
  rectangle5: "div";
  rectangle6: "div";
  menu12: "div";
  bg3: "div";
  frame1492878821: "div";
  title2: "div";
  coffee: "div";
  buttonAdd2: "div";
  frame149287856: "div";
  rectangle7: "div";
  rectangle8: "div";
  frame149287848: "div";
  menu13: "div";
  frame149287866: "div";
  alarm: "div";
  buttonAdd3: "div";
  frame149287857: "div";
  rectangle10: "div";
  rectangle11: "div";
  bg4: "div";
  skelet1: "div";
  menu14: "div";
  bg5: "div";
  skelet11: "div";
  frame149287867: "div";
  calendarRemove: "div";
  buttonAdd4: "div";
  frame149287858: "div";
  rectangle12: "div";
  rectangle13: "div";
  menu15: "div";
  bg6: "div";
  skelet21: "div";
  frame149287868: "div";
  cloudRemove: "div";
  buttonAdd5: "div";
  frame149287859: "div";
  rectangle14: "div";
  rectangle15: "div";
  about: "div";
  frame149287869: "div";
  button2: "div";
  freeBox: "div";
  closeMd: "div";
  buttonText2: "div";
  frame149287815: "div";
  button3: "div";
  usersGroup: "div";
  buttonText3: "div";
  calendar2: "div";
  button4: "div";
  uDoc: "div";
  buttonText4: "div";
  calendar3: "div";
  header: "div";
  logo: "div";
  frame596: "a";
  frame598: "div";
  rectangle1555: "div";
  button5: "div";
  iconPlaceholder2: "div";
  buttonText5: "div";
  exit: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    conciliumDefault: makeNodeComponent("conciliumDefault"),
    frame149287840: makeNodeComponent("frame149287840"),
    image3: makeNodeComponent("image3"),
    image2: makeNodeComponent("image2"),
    image4: makeNodeComponent("image4"),
    frame149287627: makeNodeComponent("frame149287627"),
    frame149287621: makeNodeComponent("frame149287621"),
    image5: makeNodeComponent("image5"),
    bottomPanel: makeNodeComponent("bottomPanel"),
    frame149287813: makeNodeComponent("frame149287813"),
    выбрано3: makeNodeComponent("\u0432\u044b\u0431\u0440\u0430\u043d\u043e3"),
    button: makeNodeComponent("button"),
    iconPlaceholder: makeNodeComponent("iconPlaceholder"),
    buttonText: makeNodeComponent("buttonText"),
    calendar: makeNodeComponent("calendar"),
    menuItemList: makeNodeComponent("menuItemList"),
    menuItem: makeNodeComponent("menuItem"),
    frame149287850: makeNodeComponent("frame149287850"),
    chevronRight: makeNodeComponent("chevronRight"),
    menuItem2: makeNodeComponent("menuItem2"),
    frame149287851: makeNodeComponent("frame149287851"),
    тяжелаяЛжнНеобходимостьВаЭкмо1: makeNodeComponent(
      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e1"
    ),
    чквВаЭкмо1: makeNodeComponent(
      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e1"
    ),
    chevronRight2: makeNodeComponent("chevronRight2"),
    menuItem3: makeNodeComponent("menuItem3"),
    frame149287852: makeNodeComponent("frame149287852"),
    тяжелаяЛжнНеобходимостьВаЭкмо2: makeNodeComponent(
      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e2"
    ),
    чквВаЭкмо2: makeNodeComponent(
      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e2"
    ),
    chevronRight3: makeNodeComponent("chevronRight3"),
    menuItem4: makeNodeComponent("menuItem4"),
    frame149287853: makeNodeComponent("frame149287853"),
    тяжелаяЛжнНеобходимостьВаЭкмо3: makeNodeComponent(
      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e3"
    ),
    чквВаЭкмо3: makeNodeComponent(
      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e3"
    ),
    chevronRight4: makeNodeComponent("chevronRight4"),
    component90: makeNodeComponent("component90"),
    frame149287854: makeNodeComponent("frame149287854"),
    тяжелаяЛжнНеобходимостьВаЭкмо4: makeNodeComponent(
      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e4"
    ),
    чквВаЭкмо4: makeNodeComponent(
      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e4"
    ),
    chevronRight5: makeNodeComponent("chevronRight5"),
    component91: makeNodeComponent("component91"),
    frame149287855: makeNodeComponent("frame149287855"),
    тяжелаяЛжнНеобходимостьВаЭкмо: makeNodeComponent(
      "\u0442\u044f\u0436\u0435\u043b\u0430\u044f\u041b\u0436\u043d\u041d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c\u0412\u0430\u042d\u043a\u043c\u043e"
    ),
    чквВаЭкмо: makeNodeComponent(
      "\u0447\u043a\u0432\u0412\u0430\u042d\u043a\u043c\u043e"
    ),
    chevronRight6: makeNodeComponent("chevronRight6"),
    frame149287864: makeNodeComponent("frame149287864"),
    frame149287847: makeNodeComponent("frame149287847"),
    menu1: makeNodeComponent("menu1"),
    bg: makeNodeComponent("bg"),
    lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11: makeNodeComponent(
      "lucidOrigin3DRenderSideProfileOfAnElegantFemaleDocto11"
    ),
    rectangle9: makeNodeComponent("rectangle9"),
    frame1492878811: makeNodeComponent("frame1492878811"),
    bg2: makeNodeComponent("bg2"),
    frame1492878812: makeNodeComponent("frame1492878812"),
    title: makeNodeComponent("title"),
    bellRing: makeNodeComponent("bellRing"),
    buttonAdd: makeNodeComponent("buttonAdd"),
    frame149287849: makeNodeComponent("frame149287849"),
    rectangle5: makeNodeComponent("rectangle5"),
    rectangle6: makeNodeComponent("rectangle6"),
    menu12: makeNodeComponent("menu12"),
    bg3: makeNodeComponent("bg3"),
    frame1492878821: makeNodeComponent("frame1492878821"),
    title2: makeNodeComponent("title2"),
    coffee: makeNodeComponent("coffee"),
    buttonAdd2: makeNodeComponent("buttonAdd2"),
    frame149287856: makeNodeComponent("frame149287856"),
    rectangle7: makeNodeComponent("rectangle7"),
    rectangle8: makeNodeComponent("rectangle8"),
    frame149287848: makeNodeComponent("frame149287848"),
    menu13: makeNodeComponent("menu13"),
    frame149287866: makeNodeComponent("frame149287866"),
    alarm: makeNodeComponent("alarm"),
    buttonAdd3: makeNodeComponent("buttonAdd3"),
    frame149287857: makeNodeComponent("frame149287857"),
    rectangle10: makeNodeComponent("rectangle10"),
    rectangle11: makeNodeComponent("rectangle11"),
    bg4: makeNodeComponent("bg4"),
    skelet1: makeNodeComponent("skelet1"),
    menu14: makeNodeComponent("menu14"),
    bg5: makeNodeComponent("bg5"),
    skelet11: makeNodeComponent("skelet11"),
    frame149287867: makeNodeComponent("frame149287867"),
    calendarRemove: makeNodeComponent("calendarRemove"),
    buttonAdd4: makeNodeComponent("buttonAdd4"),
    frame149287858: makeNodeComponent("frame149287858"),
    rectangle12: makeNodeComponent("rectangle12"),
    rectangle13: makeNodeComponent("rectangle13"),
    menu15: makeNodeComponent("menu15"),
    bg6: makeNodeComponent("bg6"),
    skelet21: makeNodeComponent("skelet21"),
    frame149287868: makeNodeComponent("frame149287868"),
    cloudRemove: makeNodeComponent("cloudRemove"),
    buttonAdd5: makeNodeComponent("buttonAdd5"),
    frame149287859: makeNodeComponent("frame149287859"),
    rectangle14: makeNodeComponent("rectangle14"),
    rectangle15: makeNodeComponent("rectangle15"),
    about: makeNodeComponent("about"),
    frame149287869: makeNodeComponent("frame149287869"),
    button2: makeNodeComponent("button2"),
    freeBox: makeNodeComponent("freeBox"),
    closeMd: makeNodeComponent("closeMd"),
    buttonText2: makeNodeComponent("buttonText2"),
    frame149287815: makeNodeComponent("frame149287815"),
    button3: makeNodeComponent("button3"),
    usersGroup: makeNodeComponent("usersGroup"),
    buttonText3: makeNodeComponent("buttonText3"),
    calendar2: makeNodeComponent("calendar2"),
    button4: makeNodeComponent("button4"),
    uDoc: makeNodeComponent("uDoc"),
    buttonText4: makeNodeComponent("buttonText4"),
    calendar3: makeNodeComponent("calendar3"),
    header: makeNodeComponent("header"),
    logo: makeNodeComponent("logo"),
    frame596: makeNodeComponent("frame596"),
    frame598: makeNodeComponent("frame598"),
    rectangle1555: makeNodeComponent("rectangle1555"),
    button5: makeNodeComponent("button5"),
    iconPlaceholder2: makeNodeComponent("iconPlaceholder2"),
    buttonText5: makeNodeComponent("buttonText5"),
    exit: makeNodeComponent("exit"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pagePath: "/",
      searchParams: {},
      params: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
