// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicHeadRightModul,
  DefaultHeadRightModulProps
} from "./plasmic/personal_acc_v_2_0_0/PlasmicHeadRightModul";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HeadRightModulProps extends Omit<DefaultHeadRightModulProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHeadRightModulProps altogether and have
// total control over the props for your component.
export interface HeadRightModulProps extends DefaultHeadRightModulProps {}

function HeadRightModul_(
  props: HeadRightModulProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicHeadRightModul to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHeadRightModul are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all HeadRightModulProps here, but feel free
  // to do whatever works for you.

  return <PlasmicHeadRightModul dinamicsModul={{ ref }} {...props} />;
}

const HeadRightModul = React.forwardRef(HeadRightModul_);
export default HeadRightModul;
