/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: 14gnl-eYPcLg

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicHeader.module.css"; // plasmic-import: 14gnl-eYPcLg/css

import Rectangle1556Icon from "../blank_project/icons/PlasmicIcon__Rectangle1556"; // plasmic-import: eE_fHLsxz0Ec/icon
import Vector2Icon from "../blank_project/icons/PlasmicIcon__Vector2"; // plasmic-import: EZENRxJYAdTV/icon
import Frame599Icon from "../blank_project/icons/PlasmicIcon__Frame599"; // plasmic-import: Zv3Kgwk3PrOp/icon
import InterfaceExitIcon from "../blank_project/icons/PlasmicIcon__InterfaceExit"; // plasmic-import: ZMti0_VkdAkc/icon

createPlasmicElementProxy;

export type PlasmicHeader__VariantMembers = {};
export type PlasmicHeader__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeader__VariantsArgs;
export const PlasmicHeader__VariantProps = new Array<VariantPropType>();

export type PlasmicHeader__ArgsType = {};
type ArgPropType = keyof PlasmicHeader__ArgsType;
export const PlasmicHeader__ArgProps = new Array<ArgPropType>();

export type PlasmicHeader__OverridesType = {
  header2?: Flex__<"div">;
  container?: Flex__<"div">;
  logo?: Flex__<"div">;
  frame596?: Flex__<"a">;
  frame598?: Flex__<"div">;
  rectangle1555?: Flex__<"div">;
  button5?: Flex__<"div">;
  iconPlaceholder2?: Flex__<"div">;
  buttonText5?: Flex__<"div">;
  exit?: Flex__<"div">;
};

export interface DefaultHeaderProps {
  className?: string;
}

const $$ = {};

function PlasmicHeader__RenderFunc(props: {
  variants: PlasmicHeader__VariantsArgs;
  args: PlasmicHeader__ArgsType;
  overrides: PlasmicHeader__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"header2"}
      data-plasmic-override={overrides.header2}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.header2
      )}
    >
      <div
        data-plasmic-name={"container"}
        data-plasmic-override={overrides.container}
        className={classNames(projectcss.all, sty.container)}
      >
        <div
          data-plasmic-name={"logo"}
          data-plasmic-override={overrides.logo}
          className={classNames(projectcss.all, sty.logo)}
        >
          <PlasmicLink__
            data-plasmic-name={"frame596"}
            data-plasmic-override={overrides.frame596}
            className={classNames(projectcss.all, projectcss.a, sty.frame596)}
            href={`/`}
            platform={"react"}
          >
            <div
              data-plasmic-name={"frame598"}
              data-plasmic-override={overrides.frame598}
              className={classNames(projectcss.all, sty.frame598)}
            >
              <Rectangle1556Icon
                className={classNames(projectcss.all, sty.svg__iryMv)}
                role={"img"}
              />

              <Vector2Icon
                className={classNames(projectcss.all, sty.svg__ypLa5)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle1555"}
                data-plasmic-override={overrides.rectangle1555}
                className={classNames(projectcss.all, sty.rectangle1555)}
              />
            </div>
            <Frame599Icon
              className={classNames(projectcss.all, sty.svg__fGhjk)}
              role={"img"}
            />
          </PlasmicLink__>
        </div>
        <div
          data-plasmic-name={"button5"}
          data-plasmic-override={overrides.button5}
          className={classNames(projectcss.all, sty.button5)}
        >
          {false ? (
            <div
              data-plasmic-name={"iconPlaceholder2"}
              data-plasmic-override={overrides.iconPlaceholder2}
              className={classNames(projectcss.all, sty.iconPlaceholder2)}
            />
          ) : null}
          <div
            data-plasmic-name={"buttonText5"}
            data-plasmic-override={overrides.buttonText5}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.buttonText5
            )}
          >
            {"\u0412\u044b\u0439\u0442\u0438"}
          </div>
          <div
            data-plasmic-name={"exit"}
            data-plasmic-override={overrides.exit}
            className={classNames(projectcss.all, sty.exit)}
          >
            <InterfaceExitIcon
              className={classNames(projectcss.all, sty.svg___49ReP)}
              role={"img"}
            />
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  header2: [
    "header2",
    "container",
    "logo",
    "frame596",
    "frame598",
    "rectangle1555",
    "button5",
    "iconPlaceholder2",
    "buttonText5",
    "exit"
  ],
  container: [
    "container",
    "logo",
    "frame596",
    "frame598",
    "rectangle1555",
    "button5",
    "iconPlaceholder2",
    "buttonText5",
    "exit"
  ],
  logo: ["logo", "frame596", "frame598", "rectangle1555"],
  frame596: ["frame596", "frame598", "rectangle1555"],
  frame598: ["frame598", "rectangle1555"],
  rectangle1555: ["rectangle1555"],
  button5: ["button5", "iconPlaceholder2", "buttonText5", "exit"],
  iconPlaceholder2: ["iconPlaceholder2"],
  buttonText5: ["buttonText5"],
  exit: ["exit"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  header2: "div";
  container: "div";
  logo: "div";
  frame596: "a";
  frame598: "div";
  rectangle1555: "div";
  button5: "div";
  iconPlaceholder2: "div";
  buttonText5: "div";
  exit: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeader__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeader__VariantsArgs;
    args?: PlasmicHeader__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeader__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeader__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeader__ArgProps,
          internalVariantPropNames: PlasmicHeader__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeader__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "header2") {
    func.displayName = "PlasmicHeader";
  } else {
    func.displayName = `PlasmicHeader.${nodeName}`;
  }
  return func;
}

export const PlasmicHeader = Object.assign(
  // Top-level PlasmicHeader renders the root element
  makeNodeComponent("header2"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    logo: makeNodeComponent("logo"),
    frame596: makeNodeComponent("frame596"),
    frame598: makeNodeComponent("frame598"),
    rectangle1555: makeNodeComponent("rectangle1555"),
    button5: makeNodeComponent("button5"),
    iconPlaceholder2: makeNodeComponent("iconPlaceholder2"),
    buttonText5: makeNodeComponent("buttonText5"),
    exit: makeNodeComponent("exit"),

    // Metadata about props expected for PlasmicHeader
    internalVariantProps: PlasmicHeader__VariantProps,
    internalArgProps: PlasmicHeader__ArgProps
  }
);

export default PlasmicHeader;
/* prettier-ignore-end */
