/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: N9Hx1TT-AY0A

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicAbout.module.css"; // plasmic-import: N9Hx1TT-AY0A/css

import MenuCloseMdIcon from "../blank_project/icons/PlasmicIcon__MenuCloseMd"; // plasmic-import: ov_pm5ZDY9Dq/icon
import UserUsersGroupIcon from "../blank_project/icons/PlasmicIcon__UserUsersGroup"; // plasmic-import: 8YYbEIpiqksB/icon
import CalendarCalendarIcon from "../blank_project/icons/PlasmicIcon__CalendarCalendar"; // plasmic-import: 955Rrjp1RWUL/icon
import FileFileDocumentIcon from "../blank_project/icons/PlasmicIcon__FileFileDocument"; // plasmic-import: UkJSgGjmh3C0/icon
import VectorIcon from "../blank_project/icons/PlasmicIcon__Vector"; // plasmic-import: mix-DtREsHLZ/icon

createPlasmicElementProxy;

export type PlasmicAbout__VariantMembers = {};
export type PlasmicAbout__VariantsArgs = {};
type VariantPropType = keyof PlasmicAbout__VariantsArgs;
export const PlasmicAbout__VariantProps = new Array<VariantPropType>();

export type PlasmicAbout__ArgsType = {};
type ArgPropType = keyof PlasmicAbout__ArgsType;
export const PlasmicAbout__ArgProps = new Array<ArgPropType>();

export type PlasmicAbout__OverridesType = {
  about?: Flex__<"div">;
  number?: Flex__<"div">;
  button2?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  closeMd?: Flex__<"div">;
  buttonText2?: Flex__<"div">;
  btnGroup?: Flex__<"div">;
  button3?: Flex__<"div">;
  usersGroup?: Flex__<"div">;
  buttonText3?: Flex__<"div">;
  calendar2?: Flex__<"div">;
  button4?: Flex__<"div">;
  uDoc?: Flex__<"div">;
  buttonText4?: Flex__<"div">;
  calendar3?: Flex__<"div">;
};

export interface DefaultAboutProps {
  className?: string;
}

const $$ = {};

function PlasmicAbout__RenderFunc(props: {
  variants: PlasmicAbout__VariantsArgs;
  args: PlasmicAbout__ArgsType;
  overrides: PlasmicAbout__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"about"}
      data-plasmic-override={overrides.about}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.about
      )}
    >
      <div
        data-plasmic-name={"number"}
        data-plasmic-override={overrides.number}
        className={classNames(projectcss.all, sty.number)}
      >
        <div
          data-plasmic-name={"button2"}
          data-plasmic-override={overrides.button2}
          className={classNames(projectcss.all, sty.button2)}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              data-plasmic-name={"closeMd"}
              data-plasmic-override={overrides.closeMd}
              className={classNames(projectcss.all, sty.closeMd)}
            >
              <MenuCloseMdIcon
                className={classNames(projectcss.all, sty.svg___3H112)}
                role={"img"}
              />
            </div>
          </div>
        </div>
        <div
          data-plasmic-name={"buttonText2"}
          data-plasmic-override={overrides.buttonText2}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.buttonText2
          )}
        >
          {"8978117000081"}
        </div>
      </div>
      <div
        data-plasmic-name={"btnGroup"}
        data-plasmic-override={overrides.btnGroup}
        className={classNames(projectcss.all, sty.btnGroup)}
      >
        <div
          data-plasmic-name={"button3"}
          data-plasmic-override={overrides.button3}
          className={classNames(projectcss.all, sty.button3)}
          onClick={async event => {
            const $steps = {};

            $steps["goToConcilium"] = true
              ? (() => {
                  const actionArgs = { destination: `/` };
                  return (({ destination }) => {
                    if (
                      typeof destination === "string" &&
                      destination.startsWith("#")
                    ) {
                      document
                        .getElementById(destination.substr(1))
                        .scrollIntoView({ behavior: "smooth" });
                    } else {
                      location.assign(destination);
                    }
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["goToConcilium"] != null &&
              typeof $steps["goToConcilium"] === "object" &&
              typeof $steps["goToConcilium"].then === "function"
            ) {
              $steps["goToConcilium"] = await $steps["goToConcilium"];
            }
          }}
        >
          <div
            data-plasmic-name={"usersGroup"}
            data-plasmic-override={overrides.usersGroup}
            className={classNames(projectcss.all, sty.usersGroup)}
          >
            <UserUsersGroupIcon
              className={classNames(projectcss.all, sty.svg___33Pps)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"buttonText3"}
            data-plasmic-override={overrides.buttonText3}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.buttonText3
            )}
          >
            {
              "\u0420\u0435\u0436\u0438\u043c \u043a\u043e\u043d\u0441\u0438\u043b\u0438\u0443\u043c\u0430"
            }
          </div>
          {false ? (
            <div
              data-plasmic-name={"calendar2"}
              data-plasmic-override={overrides.calendar2}
              className={classNames(projectcss.all, sty.calendar2)}
            >
              <CalendarCalendarIcon
                className={classNames(projectcss.all, sty.svg__mWg27)}
                role={"img"}
              />
            </div>
          ) : null}
        </div>
        <div
          data-plasmic-name={"button4"}
          data-plasmic-override={overrides.button4}
          className={classNames(projectcss.all, sty.button4)}
        >
          <div
            data-plasmic-name={"uDoc"}
            data-plasmic-override={overrides.uDoc}
            className={classNames(projectcss.all, sty.uDoc)}
          >
            <FileFileDocumentIcon
              className={classNames(projectcss.all, sty.svg__j3FQl)}
              role={"img"}
            />

            <VectorIcon
              className={classNames(projectcss.all, sty.svg__pd08C)}
              role={"img"}
            />

            <VectorIcon
              className={classNames(projectcss.all, sty.svg___6Xyuu)}
              role={"img"}
            />
          </div>
          <div
            data-plasmic-name={"buttonText4"}
            data-plasmic-override={overrides.buttonText4}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.buttonText4
            )}
          >
            {
              "\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u044d\u043f\u0438\u043a\u0440\u0438\u0437"
            }
          </div>
          {false ? (
            <div
              data-plasmic-name={"calendar3"}
              data-plasmic-override={overrides.calendar3}
              className={classNames(projectcss.all, sty.calendar3)}
            >
              <CalendarCalendarIcon
                className={classNames(projectcss.all, sty.svg__eQrx)}
                role={"img"}
              />
            </div>
          ) : null}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  about: [
    "about",
    "number",
    "button2",
    "freeBox",
    "closeMd",
    "buttonText2",
    "btnGroup",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3"
  ],
  number: ["number", "button2", "freeBox", "closeMd", "buttonText2"],
  button2: ["button2", "freeBox", "closeMd"],
  freeBox: ["freeBox", "closeMd"],
  closeMd: ["closeMd"],
  buttonText2: ["buttonText2"],
  btnGroup: [
    "btnGroup",
    "button3",
    "usersGroup",
    "buttonText3",
    "calendar2",
    "button4",
    "uDoc",
    "buttonText4",
    "calendar3"
  ],
  button3: ["button3", "usersGroup", "buttonText3", "calendar2"],
  usersGroup: ["usersGroup"],
  buttonText3: ["buttonText3"],
  calendar2: ["calendar2"],
  button4: ["button4", "uDoc", "buttonText4", "calendar3"],
  uDoc: ["uDoc"],
  buttonText4: ["buttonText4"],
  calendar3: ["calendar3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  about: "div";
  number: "div";
  button2: "div";
  freeBox: "div";
  closeMd: "div";
  buttonText2: "div";
  btnGroup: "div";
  button3: "div";
  usersGroup: "div";
  buttonText3: "div";
  calendar2: "div";
  button4: "div";
  uDoc: "div";
  buttonText4: "div";
  calendar3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAbout__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAbout__VariantsArgs;
    args?: PlasmicAbout__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicAbout__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicAbout__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicAbout__ArgProps,
          internalVariantPropNames: PlasmicAbout__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicAbout__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "about") {
    func.displayName = "PlasmicAbout";
  } else {
    func.displayName = `PlasmicAbout.${nodeName}`;
  }
  return func;
}

export const PlasmicAbout = Object.assign(
  // Top-level PlasmicAbout renders the root element
  makeNodeComponent("about"),
  {
    // Helper components rendering sub-elements
    number: makeNodeComponent("number"),
    button2: makeNodeComponent("button2"),
    freeBox: makeNodeComponent("freeBox"),
    closeMd: makeNodeComponent("closeMd"),
    buttonText2: makeNodeComponent("buttonText2"),
    btnGroup: makeNodeComponent("btnGroup"),
    button3: makeNodeComponent("button3"),
    usersGroup: makeNodeComponent("usersGroup"),
    buttonText3: makeNodeComponent("buttonText3"),
    calendar2: makeNodeComponent("calendar2"),
    button4: makeNodeComponent("button4"),
    uDoc: makeNodeComponent("uDoc"),
    buttonText4: makeNodeComponent("buttonText4"),
    calendar3: makeNodeComponent("calendar3"),

    // Metadata about props expected for PlasmicAbout
    internalVariantProps: PlasmicAbout__VariantProps,
    internalArgProps: PlasmicAbout__ArgProps
  }
);

export default PlasmicAbout;
/* prettier-ignore-end */
