/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: F3O-s0wbfh7V

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicSectionItemM.module.css"; // plasmic-import: F3O-s0wbfh7V/css

import CommunicationBellRingIcon from "../blank_project/icons/PlasmicIcon__CommunicationBellRing"; // plasmic-import: yRUitfzQMAry/icon
import IconPlusSvgIcon from "./icons/PlasmicIcon__IconPlusSvg"; // plasmic-import: oux8kujogT8a/icon
import IconSuccessSvgIcon from "./icons/PlasmicIcon__IconSuccessSvg"; // plasmic-import: K5Fu1GNigI67/icon

createPlasmicElementProxy;

export type PlasmicSectionItemM__VariantMembers = {
  active: "active";
};
export type PlasmicSectionItemM__VariantsArgs = {
  active?: SingleBooleanChoiceArg<"active">;
};
type VariantPropType = keyof PlasmicSectionItemM__VariantsArgs;
export const PlasmicSectionItemM__VariantProps = new Array<VariantPropType>(
  "active"
);

export type PlasmicSectionItemM__ArgsType = {
  itemId?: string;
  imgSection12?: React.ReactNode;
  bellRing2?: React.ReactNode;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicSectionItemM__ArgsType;
export const PlasmicSectionItemM__ArgProps = new Array<ArgPropType>(
  "itemId",
  "imgSection12",
  "bellRing2",
  "children"
);

export type PlasmicSectionItemM__OverridesType = {
  menu1?: Flex__<"div">;
  imgSection1?: Flex__<"div">;
  title?: Flex__<"div">;
  sectionIcon?: Flex__<"div">;
  buttonAdd?: Flex__<"div">;
  svg?: Flex__<"svg">;
};

export interface DefaultSectionItemMProps {
  itemId?: string;
  imgSection12?: React.ReactNode;
  bellRing2?: React.ReactNode;
  children?: React.ReactNode;
  active?: SingleBooleanChoiceArg<"active">;
  className?: string;
}

const $$ = {};

function PlasmicSectionItemM__RenderFunc(props: {
  variants: PlasmicSectionItemM__VariantsArgs;
  args: PlasmicSectionItemM__ArgsType;
  overrides: PlasmicSectionItemM__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "active",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.active
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"menu1"}
      data-plasmic-override={overrides.menu1}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.menu1,
        { [sty.menu1active]: hasVariant($state, "active", "active") }
      )}
      data-itemid={$props.itemId}
      onClick={async event => {
        const $steps = {};

        $steps["updateActive"] = true
          ? (() => {
              const actionArgs = {
                vgroup: "active",
                operation: 2,
                value: "active"
              };
              return (({ vgroup, value }) => {
                if (typeof value === "string") {
                  value = [value];
                }

                const oldValue = $stateGet($state, vgroup);
                $stateSet($state, vgroup, !oldValue);
                return !oldValue;
              })?.apply(null, [actionArgs]);
            })()
          : undefined;
        if (
          $steps["updateActive"] != null &&
          typeof $steps["updateActive"] === "object" &&
          typeof $steps["updateActive"].then === "function"
        ) {
          $steps["updateActive"] = await $steps["updateActive"];
        }
      }}
    >
      <div
        data-plasmic-name={"imgSection1"}
        data-plasmic-override={overrides.imgSection1}
        className={classNames(projectcss.all, sty.imgSection1, {
          [sty.imgSection1active]: hasVariant($state, "active", "active")
        })}
      >
        {renderPlasmicSlot({
          defaultContents: null,
          value: args.imgSection12
        })}
      </div>
      <div
        data-plasmic-name={"title"}
        data-plasmic-override={overrides.title}
        className={classNames(projectcss.all, sty.title)}
      >
        <div
          data-plasmic-name={"sectionIcon"}
          data-plasmic-override={overrides.sectionIcon}
          className={classNames(projectcss.all, sty.sectionIcon)}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <CommunicationBellRingIcon
                className={classNames(projectcss.all, sty.svg__wRed1)}
                role={"img"}
              />
            ),

            value: args.bellRing2
          })}
        </div>
        {renderPlasmicSlot({
          defaultContents:
            "\u041a\u043e\u043d\u0441\u0443\u043b\u044c\u0442\u0430\u0446\u0438\u0438",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenactive]: hasVariant(
              $state,
              "active",
              "active"
            )
          })
        })}
      </div>
      <div
        data-plasmic-name={"buttonAdd"}
        data-plasmic-override={overrides.buttonAdd}
        className={classNames(projectcss.all, sty.buttonAdd, {
          [sty.buttonAddactive]: hasVariant($state, "active", "active")
        })}
      >
        <PlasmicIcon__
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          PlasmicIconType={
            hasVariant($state, "active", "active")
              ? IconSuccessSvgIcon
              : IconPlusSvgIcon
          }
          className={classNames(projectcss.all, sty.svg, {
            [sty.svgactive]: hasVariant($state, "active", "active")
          })}
          role={"img"}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  menu1: ["menu1", "imgSection1", "title", "sectionIcon", "buttonAdd", "svg"],
  imgSection1: ["imgSection1"],
  title: ["title", "sectionIcon"],
  sectionIcon: ["sectionIcon"],
  buttonAdd: ["buttonAdd", "svg"],
  svg: ["svg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  menu1: "div";
  imgSection1: "div";
  title: "div";
  sectionIcon: "div";
  buttonAdd: "div";
  svg: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSectionItemM__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSectionItemM__VariantsArgs;
    args?: PlasmicSectionItemM__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSectionItemM__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSectionItemM__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSectionItemM__ArgProps,
          internalVariantPropNames: PlasmicSectionItemM__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSectionItemM__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "menu1") {
    func.displayName = "PlasmicSectionItemM";
  } else {
    func.displayName = `PlasmicSectionItemM.${nodeName}`;
  }
  return func;
}

export const PlasmicSectionItemM = Object.assign(
  // Top-level PlasmicSectionItemM renders the root element
  makeNodeComponent("menu1"),
  {
    // Helper components rendering sub-elements
    imgSection1: makeNodeComponent("imgSection1"),
    title: makeNodeComponent("title"),
    sectionIcon: makeNodeComponent("sectionIcon"),
    buttonAdd: makeNodeComponent("buttonAdd"),
    svg: makeNodeComponent("svg"),

    // Metadata about props expected for PlasmicSectionItemM
    internalVariantProps: PlasmicSectionItemM__VariantProps,
    internalArgProps: PlasmicSectionItemM__ArgProps
  }
);

export default PlasmicSectionItemM;
/* prettier-ignore-end */
