/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: DfUbWaaGRLVN

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeadRightModul from "../../HeadRightModul"; // plasmic-import: p2Y85AioaQIm/component
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicDraft.module.css"; // plasmic-import: DfUbWaaGRLVN/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicDraft__VariantMembers = {};
export type PlasmicDraft__VariantsArgs = {};
type VariantPropType = keyof PlasmicDraft__VariantsArgs;
export const PlasmicDraft__VariantProps = new Array<VariantPropType>();

export type PlasmicDraft__ArgsType = {};
type ArgPropType = keyof PlasmicDraft__ArgsType;
export const PlasmicDraft__ArgProps = new Array<ArgPropType>();

export type PlasmicDraft__OverridesType = {
  root?: Flex__<"div">;
  headRightModul?: Flex__<typeof HeadRightModul>;
};

export interface DefaultDraftProps {
  className?: string;
}

const $$ = {};

function PlasmicDraft__RenderFunc(props: {
  variants: PlasmicDraft__VariantsArgs;
  args: PlasmicDraft__ArgsType;
  overrides: PlasmicDraft__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <HeadRightModul
            data-plasmic-name={"headRightModul"}
            data-plasmic-override={overrides.headRightModul}
            className={classNames("__wab_instance", sty.headRightModul)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "headRightModul"],
  headRightModul: ["headRightModul"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headRightModul: typeof HeadRightModul;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDraft__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDraft__VariantsArgs;
    args?: PlasmicDraft__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDraft__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDraft__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDraft__ArgProps,
          internalVariantPropNames: PlasmicDraft__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDraft__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDraft";
  } else {
    func.displayName = `PlasmicDraft.${nodeName}`;
  }
  return func;
}

export const PlasmicDraft = Object.assign(
  // Top-level PlasmicDraft renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headRightModul: makeNodeComponent("headRightModul"),

    // Metadata about props expected for PlasmicDraft
    internalVariantProps: PlasmicDraft__VariantProps,
    internalArgProps: PlasmicDraft__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/new-page",
      pagePath: "/new-page",
      params: {},
      query: {}
    })
  }
);

export default PlasmicDraft;
/* prettier-ignore-end */
