/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: KynzDgv1-NaR

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import HeadRightModul from "../../HeadRightModul"; // plasmic-import: p2Y85AioaQIm/component
import Header from "../../Header"; // plasmic-import: 14gnl-eYPcLg/component
import About from "../../About"; // plasmic-import: N9Hx1TT-AY0A/component
import MenuItem from "../../MenuItem"; // plasmic-import: uDgGFisdmU9o/component
import SectionItemL from "../../SectionItemL"; // plasmic-import: xMkRB3Moyr1q/component
import SectionItemM from "../../SectionItemM"; // plasmic-import: F3O-s0wbfh7V/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicConcilium.module.css"; // plasmic-import: KynzDgv1-NaR/css

import CommunicationBellRingIcon from "../blank_project/icons/PlasmicIcon__CommunicationBellRing"; // plasmic-import: yRUitfzQMAry/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicConcilium__VariantMembers = {};
export type PlasmicConcilium__VariantsArgs = {};
type VariantPropType = keyof PlasmicConcilium__VariantsArgs;
export const PlasmicConcilium__VariantProps = new Array<VariantPropType>();

export type PlasmicConcilium__ArgsType = {};
type ArgPropType = keyof PlasmicConcilium__ArgsType;
export const PlasmicConcilium__ArgProps = new Array<ArgPropType>();

export type PlasmicConcilium__OverridesType = {
  root?: Flex__<"div">;
  headRightModul?: Flex__<typeof HeadRightModul>;
  header?: Flex__<typeof Header>;
  wraper?: Flex__<"div">;
  container2?: Flex__<"div">;
  about?: Flex__<typeof About>;
  container?: Flex__<"div">;
  menuItemList?: Flex__<"div">;
  tileMainList?: Flex__<"div">;
  row?: Flex__<"div">;
  row2?: Flex__<"div">;
};

export interface DefaultConciliumProps {
  className?: string;
}

const $$ = {};

function PlasmicConcilium__RenderFunc(props: {
  variants: PlasmicConcilium__VariantsArgs;
  args: PlasmicConcilium__ArgsType;
  overrides: PlasmicConcilium__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            styleTokensClassNames,
            sty.root
          )}
        >
          <HeadRightModul
            data-plasmic-name={"headRightModul"}
            data-plasmic-override={overrides.headRightModul}
            className={classNames("__wab_instance", sty.headRightModul)}
            opened={true}
          />

          <Header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("__wab_instance", sty.header)}
          />

          <div
            data-plasmic-name={"wraper"}
            data-plasmic-override={overrides.wraper}
            className={classNames(projectcss.all, sty.wraper)}
          >
            <div
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              className={classNames(projectcss.all, sty.container2)}
            >
              <About
                data-plasmic-name={"about"}
                data-plasmic-override={overrides.about}
                className={classNames("__wab_instance", sty.about)}
              />
            </div>
          </div>
          <div
            data-plasmic-name={"container"}
            data-plasmic-override={overrides.container}
            className={classNames(projectcss.all, sty.container)}
          >
            <div
              data-plasmic-name={"menuItemList"}
              data-plasmic-override={overrides.menuItemList}
              className={classNames(projectcss.all, sty.menuItemList)}
            >
              <MenuItem
                className={classNames("__wab_instance", sty.menuItem__m5Ea6)}
              />

              <MenuItem
                className={classNames("__wab_instance", sty.menuItem__rOnt9)}
                slot={
                  "\u0421\u0442\u0432\u043e\u043b \u041b\u041a\u0410: 85\u201390% \u0441\u0442\u0435\u043d\u043e\u0437"
                }
              >
                {
                  "\u041c\u043d\u043e\u0433\u043e\u0441\u043e\u0441\u0443\u0434\u0438\u0441\u0442\u0430\u044f \u043a\u043e\u0440\u043e\u043d\u0430\u0440\u043d\u0430\u044f \u0431\u043e\u043b\u0435\u0437\u043d\u044c \u0441 \u043a\u0430\u043b\u044c\u0446\u0438\u043d\u043e\u0437\u043e\u043c"
                }
              </MenuItem>
              <MenuItem
                className={classNames("__wab_instance", sty.menuItem__rPcps)}
                slot={
                  "\u0422\u044f\u0436\u0435\u043b\u044b\u0439 \u0430\u043e\u0440\u0442\u0430\u043b\u044c\u043d\u044b\u0439 \u0441\u0442\u0435\u043d\u043e\u0437"
                }
              >
                {
                  "\u041f\u0440\u043e\u0433\u0440\u0435\u0441\u0441\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435 \u0430\u043e\u0440\u0442\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u0441\u0442\u0435\u043d\u043e\u0437\u0430"
                }
              </MenuItem>
              <MenuItem
                className={classNames("__wab_instance", sty.menuItem__jthIq)}
                slot={
                  "\u041f\u0440\u0438\u0440\u043e\u0434\u0430 \u043f\u043e\u0434 \u0432\u043e\u043f\u0440\u043e\u0441\u043e\u043c"
                }
              >
                {
                  "\u0413\u0438\u043f\u0435\u0440\u044d\u0445\u043e\u0433\u0435\u043d\u043d\u044b\u0435 \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b \u0432 \u041d\u041f\u0412/\u043f\u0440\u0430\u0432\u043e\u043c \u043f\u0440\u0435\u0434\u0441\u0435\u0440\u0434\u0438\u0438 (\u0442\u0440\u043e\u043c\u0431\u044b? \u043a\u0430\u043b\u044c\u0446\u0438\u043d\u043e\u0437?)"
                }
              </MenuItem>
              <MenuItem
                className={classNames("__wab_instance", sty.menuItem___6SAn)}
                slot={
                  "\u0421\u0442\u0435\u043d\u043e\u0437\u044b 80\u201395% + \u0440\u0435\u0437\u043a\u043e \u0441\u043d\u0438\u0436\u0435\u043d\u043d\u0430\u044f \u0424\u0412"
                }
              >
                {
                  "\u0410\u0440\u0438\u0442\u043c\u0438\u0438 (\u0416\u042d\u0421, \u0424\u041f) \u00a0"
                }
              </MenuItem>
              <MenuItem
                className={classNames("__wab_instance", sty.menuItem__anSoP)}
                slot={
                  "\u041b\u0416\u041d + \u0432\u044b\u0441\u043e\u043a\u0438\u0435 \u0434\u043e\u0437\u044b \u0432\u0430\u0437\u043e\u043f\u0440\u0435\u0441\u0441\u043e\u0440\u043e\u0432 (NA 1,1; A 0,07)"
                }
              >
                {
                  "\u041d\u0438\u0437\u043a\u0438\u0439 \u0434\u0438\u0443\u0440\u0435\u0437, \u0440\u0438\u0441\u043a \u043f\u043e\u0447\u0435\u0447\u043d\u043e\u0439 \u0434\u0438\u0441\u0444\u0443\u043d\u043a\u0446\u0438\u0438 \u00a0"
                }
              </MenuItem>
            </div>
            <div
              data-plasmic-name={"tileMainList"}
              data-plasmic-override={overrides.tileMainList}
              className={classNames(projectcss.all, sty.tileMainList)}
            >
              <div
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                className={classNames(projectcss.all, sty.row)}
              >
                <SectionItemL
                  className={classNames(
                    "__wab_instance",
                    sty.sectionItemL__jaOdM
                  )}
                  itemId={"Large1"}
                />

                <SectionItemL
                  className={classNames(
                    "__wab_instance",
                    sty.sectionItemL__aUlfr
                  )}
                  itemId={"Large2"}
                >
                  {
                    "\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u043d\u044b\u0435"
                  }
                </SectionItemL>
              </div>
              <div
                data-plasmic-name={"row2"}
                data-plasmic-override={overrides.row2}
                className={classNames(projectcss.all, sty.row2)}
              >
                <SectionItemM
                  className={classNames(
                    "__wab_instance",
                    sty.sectionItemM__wnKqB
                  )}
                  itemId={"Medium1"}
                >
                  {
                    "\u0410\u043d\u0430\u0442\u043e\u043c\u0438\u0447\u0435\u0441\u043a\u0438\u0435"
                  }
                </SectionItemM>
                <SectionItemM
                  className={classNames(
                    "__wab_instance",
                    sty.sectionItemM__lyal1
                  )}
                  itemId={"Medium2"}
                >
                  {
                    "\u0424\u0443\u043d\u043a\u0446\u0438\u043e\u043d\u0430\u043b\u044c\u043d\u044b\u0435"
                  }
                </SectionItemM>
                <SectionItemM
                  className={classNames(
                    "__wab_instance",
                    sty.sectionItemM__x480
                  )}
                  itemId={"Medium3"}
                >
                  {
                    "\u042d\u043d\u0434\u043e\u0441\u043a\u043e\u043f\u0438\u0447\u0435\u0441\u043a\u0438\u0435"
                  }
                </SectionItemM>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "headRightModul",
    "header",
    "wraper",
    "container2",
    "about",
    "container",
    "menuItemList",
    "tileMainList",
    "row",
    "row2"
  ],
  headRightModul: ["headRightModul"],
  header: ["header"],
  wraper: ["wraper", "container2", "about"],
  container2: ["container2", "about"],
  about: ["about"],
  container: ["container", "menuItemList", "tileMainList", "row", "row2"],
  menuItemList: ["menuItemList"],
  tileMainList: ["tileMainList", "row", "row2"],
  row: ["row"],
  row2: ["row2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  headRightModul: typeof HeadRightModul;
  header: typeof Header;
  wraper: "div";
  container2: "div";
  about: typeof About;
  container: "div";
  menuItemList: "div";
  tileMainList: "div";
  row: "div";
  row2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicConcilium__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicConcilium__VariantsArgs;
    args?: PlasmicConcilium__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicConcilium__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicConcilium__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicConcilium__ArgProps,
          internalVariantPropNames: PlasmicConcilium__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicConcilium__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicConcilium";
  } else {
    func.displayName = `PlasmicConcilium.${nodeName}`;
  }
  return func;
}

export const PlasmicConcilium = Object.assign(
  // Top-level PlasmicConcilium renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headRightModul: makeNodeComponent("headRightModul"),
    header: makeNodeComponent("header"),
    wraper: makeNodeComponent("wraper"),
    container2: makeNodeComponent("container2"),
    about: makeNodeComponent("about"),
    container: makeNodeComponent("container"),
    menuItemList: makeNodeComponent("menuItemList"),
    tileMainList: makeNodeComponent("tileMainList"),
    row: makeNodeComponent("row"),
    row2: makeNodeComponent("row2"),

    // Metadata about props expected for PlasmicConcilium
    internalVariantProps: PlasmicConcilium__VariantProps,
    internalArgProps: PlasmicConcilium__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicConcilium;
/* prettier-ignore-end */
