/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: 7_jePp73DrbF

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import TextInput from "../../TextInput"; // plasmic-import: V4hyYX8r6OZY/component
import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicSearchInputFeld.module.css"; // plasmic-import: 7_jePp73DrbF/css

import CSearchIcon from "./icons/PlasmicIcon__CSearch"; // plasmic-import: xsLj7J5F-sSs/icon

createPlasmicElementProxy;

export type PlasmicSearchInputFeld__VariantMembers = {};
export type PlasmicSearchInputFeld__VariantsArgs = {};
type VariantPropType = keyof PlasmicSearchInputFeld__VariantsArgs;
export const PlasmicSearchInputFeld__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSearchInputFeld__ArgsType = {};
type ArgPropType = keyof PlasmicSearchInputFeld__ArgsType;
export const PlasmicSearchInputFeld__ArgProps = new Array<ArgPropType>();

export type PlasmicSearchInputFeld__OverridesType = {
  root?: Flex__<"div">;
  searchInputFeld?: Flex__<"div">;
  text?: Flex__<"div">;
  textInput?: Flex__<typeof TextInput>;
  img?: Flex__<typeof PlasmicImg__>;
  searchButton?: Flex__<"div">;
  svg?: Flex__<"svg">;
  errorMessage?: Flex__<"div">;
};

export interface DefaultSearchInputFeldProps {
  className?: string;
}

const $$ = {};

function PlasmicSearchInputFeld__RenderFunc(props: {
  variants: PlasmicSearchInputFeld__VariantsArgs;
  args: PlasmicSearchInputFeld__ArgsType;
  overrides: PlasmicSearchInputFeld__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"searchInputFeld"}
        data-plasmic-override={overrides.searchInputFeld}
        className={classNames(projectcss.all, sty.searchInputFeld)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(projectcss.all, sty.text)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__jssl5
            )}
          >
            {"ID"}
          </div>
          <TextInput
            data-plasmic-name={"textInput"}
            data-plasmic-override={overrides.textInput}
            className={classNames("__wab_instance", sty.textInput)}
            onChange={async (...eventArgs: any) => {
              generateStateOnChangeProp($state, ["textInput", "value"]).apply(
                null,
                eventArgs
              );

              if (
                eventArgs.length > 1 &&
                eventArgs[1] &&
                eventArgs[1]._plasmic_state_init_
              ) {
                return;
              }
            }}
            placeholder={
              "\u041d\u043e\u043c\u0435\u0440 \u043c\u0435\u0434\u0438\u0446\u0438\u043d\u0441\u043a\u043e\u0439 \u043a\u0430\u0440\u0442\u044b"
            }
            value={generateStateValueProp($state, ["textInput", "value"])}
          />

          <div className={classNames(projectcss.all, sty.freeBox__tTiv0)}>
            <PlasmicImg__
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"3px"}
              displayMaxHeight={"none"}
              displayMaxWidth={"100%"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"28px"}
              loading={"lazy"}
              src={{
                src: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIGZpbGw9Im5vbmUiIHZpZXdCb3g9IjAgMCAyOCAzIj4KICA8cGF0aCBzdHJva2U9IiNCM0ZGNEIiIHN0cm9rZS13aWR0aD0iMyIgZD0iTTAgMS41aDI4Ii8+CiAgPHBhdGggc3Ryb2tlPSIjMTU4MEZGIiBzdHJva2Utd2lkdGg9IjMiIGQ9Ik0wIDEuNWgyOCIvPgo8L3N2Zz4K",
                fullWidth: 28,
                fullHeight: 3
              }}
            />
          </div>
        </div>
        <div
          data-plasmic-name={"searchButton"}
          data-plasmic-override={overrides.searchButton}
          className={classNames(projectcss.all, sty.searchButton)}
        >
          <div className={classNames(projectcss.all, sty.freeBox__maS0Z)}>
            <CSearchIcon
              data-plasmic-name={"svg"}
              data-plasmic-override={overrides.svg}
              className={classNames(projectcss.all, sty.svg)}
              role={"img"}
            />
          </div>
        </div>
      </div>
      <div
        data-plasmic-name={"errorMessage"}
        data-plasmic-override={overrides.errorMessage}
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.errorMessage
        )}
      >
        {
          "\u041c\u0435\u0434\u043a\u0430\u0440\u0442\u0430 \u043f\u0430\u0446\u0438\u0435\u043d\u0442\u0430 \u043e\u0442\u0441\u0443\u0442\u0441\u0442\u0432\u0443\u0435\u0442"
        }
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "searchInputFeld",
    "text",
    "textInput",
    "img",
    "searchButton",
    "svg",
    "errorMessage"
  ],
  searchInputFeld: [
    "searchInputFeld",
    "text",
    "textInput",
    "img",
    "searchButton",
    "svg"
  ],
  text: ["text", "textInput", "img"],
  textInput: ["textInput"],
  img: ["img"],
  searchButton: ["searchButton", "svg"],
  svg: ["svg"],
  errorMessage: ["errorMessage"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  searchInputFeld: "div";
  text: "div";
  textInput: typeof TextInput;
  img: typeof PlasmicImg__;
  searchButton: "div";
  svg: "svg";
  errorMessage: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSearchInputFeld__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSearchInputFeld__VariantsArgs;
    args?: PlasmicSearchInputFeld__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSearchInputFeld__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSearchInputFeld__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSearchInputFeld__ArgProps,
          internalVariantPropNames: PlasmicSearchInputFeld__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSearchInputFeld__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSearchInputFeld";
  } else {
    func.displayName = `PlasmicSearchInputFeld.${nodeName}`;
  }
  return func;
}

export const PlasmicSearchInputFeld = Object.assign(
  // Top-level PlasmicSearchInputFeld renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    searchInputFeld: makeNodeComponent("searchInputFeld"),
    text: makeNodeComponent("text"),
    textInput: makeNodeComponent("textInput"),
    img: makeNodeComponent("img"),
    searchButton: makeNodeComponent("searchButton"),
    svg: makeNodeComponent("svg"),
    errorMessage: makeNodeComponent("errorMessage"),

    // Metadata about props expected for PlasmicSearchInputFeld
    internalVariantProps: PlasmicSearchInputFeld__VariantProps,
    internalArgProps: PlasmicSearchInputFeld__ArgProps
  }
);

export default PlasmicSearchInputFeld;
/* prettier-ignore-end */
