/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: uDgGFisdmU9o

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicMenuItem.module.css"; // plasmic-import: uDgGFisdmU9o/css

import ArrowChevronRightIcon from "../blank_project/icons/PlasmicIcon__ArrowChevronRight"; // plasmic-import: 3QDC0LyA65OX/icon
import MenuCloseMdIcon from "../blank_project/icons/PlasmicIcon__MenuCloseMd"; // plasmic-import: ov_pm5ZDY9Dq/icon

createPlasmicElementProxy;

export type PlasmicMenuItem__VariantMembers = {
  active: "active";
};
export type PlasmicMenuItem__VariantsArgs = {
  active?: SingleBooleanChoiceArg<"active">;
};
type VariantPropType = keyof PlasmicMenuItem__VariantsArgs;
export const PlasmicMenuItem__VariantProps = new Array<VariantPropType>(
  "active"
);

export type PlasmicMenuItem__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicMenuItem__ArgsType;
export const PlasmicMenuItem__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicMenuItem__OverridesType = {
  property1Default?: Flex__<"div">;
  dataContent?: Flex__<"div">;
  title?: Flex__<"div">;
  subtitle?: Flex__<"div">;
  chevronRight?: Flex__<"div">;
  property1Hover?: Flex__<"div">;
  dataContent2?: Flex__<"div">;
  title2?: Flex__<"div">;
  text?: Flex__<"div">;
  chevronRight2?: Flex__<"div">;
};

export interface DefaultMenuItemProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  active?: SingleBooleanChoiceArg<"active">;
  className?: string;
}

const $$ = {};

function PlasmicMenuItem__RenderFunc(props: {
  variants: PlasmicMenuItem__VariantsArgs;
  args: PlasmicMenuItem__ArgsType;
  overrides: PlasmicMenuItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "active",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.active
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const [isProperty1DefaultHover, triggerProperty1DefaultHoverProps] =
    useTrigger("useHover", {});
  const triggers = {
    hover_property1Default: isProperty1DefaultHover
  };

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"property1Default"}
      data-plasmic-override={overrides.property1Default}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.property1Default,
        { [sty.property1Defaultactive]: hasVariant($state, "active", "active") }
      )}
      data-plasmic-trigger-props={[triggerProperty1DefaultHoverProps]}
    >
      <div
        data-plasmic-name={"dataContent"}
        data-plasmic-override={overrides.dataContent}
        className={classNames(projectcss.all, sty.dataContent, {
          [sty.dataContentactive]: hasVariant($state, "active", "active")
        })}
      >
        <div
          data-plasmic-name={"title"}
          data-plasmic-override={overrides.title}
          className={classNames(projectcss.all, sty.title, {
            [sty.titleactive]: hasVariant($state, "active", "active")
          })}
        >
          {renderPlasmicSlot({
            defaultContents:
              "\u0422\u044f\u0436\u0435\u043b\u0430\u044f \u041b\u0416\u041d, \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0",
            value: args.children,
            className: classNames(sty.slotTargetChildren, {
              [sty.slotTargetChildrenactive]: hasVariant(
                $state,
                "active",
                "active"
              )
            })
          })}
        </div>
        <div
          data-plasmic-name={"subtitle"}
          data-plasmic-override={overrides.subtitle}
          className={classNames(projectcss.all, sty.subtitle, {
            [sty.subtitleactive]: hasVariant($state, "active", "active")
          })}
        >
          {renderPlasmicSlot({
            defaultContents:
              "\u0427\u041a\u0412 + \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0",
            value: args.slot,
            className: classNames(sty.slotTargetSlot, {
              [sty.slotTargetSlotactive]: hasVariant($state, "active", "active")
            })
          })}
        </div>
      </div>
      <div
        data-plasmic-name={"chevronRight"}
        data-plasmic-override={overrides.chevronRight}
        className={classNames(projectcss.all, sty.chevronRight, {
          [sty.chevronRightactive]: hasVariant($state, "active", "active")
        })}
      >
        <ArrowChevronRightIcon
          className={classNames(projectcss.all, sty.svg__xi1R, {
            [sty.svgactive__xi1RHg4Z]: hasVariant($state, "active", "active")
          })}
          role={"img"}
        />

        <MenuCloseMdIcon
          className={classNames(projectcss.all, sty.svg__jYn3Q, {
            [sty.svgactive__jYn3Qhg4Z]: hasVariant($state, "active", "active")
          })}
          role={"img"}
        />
      </div>
      {(triggers.hover_property1Default ? true : false) ? (
        <div
          data-plasmic-name={"property1Hover"}
          data-plasmic-override={overrides.property1Hover}
          className={classNames(projectcss.all, sty.property1Hover)}
        >
          <div
            data-plasmic-name={"dataContent2"}
            data-plasmic-override={overrides.dataContent2}
            className={classNames(projectcss.all, sty.dataContent2)}
          >
            <div
              data-plasmic-name={"title2"}
              data-plasmic-override={overrides.title2}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.title2
              )}
            >
              {
                "\u0422\u044f\u0436\u0435\u043b\u0430\u044f \u041b\u0416\u041d, \u043d\u0435\u043e\u0431\u0445\u043e\u0434\u0438\u043c\u043e\u0441\u0442\u044c \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0"
              }
            </div>
            <div
              data-plasmic-name={"text"}
              data-plasmic-override={overrides.text}
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text
              )}
            >
              {
                "\u0427\u041a\u0412 + \u0412\u0410-\u042d\u041a\u041c\u041e \u00a0"
              }
            </div>
          </div>
          <div
            data-plasmic-name={"chevronRight2"}
            data-plasmic-override={overrides.chevronRight2}
            className={classNames(projectcss.all, sty.chevronRight2)}
          />
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  property1Default: [
    "property1Default",
    "dataContent",
    "title",
    "subtitle",
    "chevronRight",
    "property1Hover",
    "dataContent2",
    "title2",
    "text",
    "chevronRight2"
  ],
  dataContent: ["dataContent", "title", "subtitle"],
  title: ["title"],
  subtitle: ["subtitle"],
  chevronRight: ["chevronRight"],
  property1Hover: [
    "property1Hover",
    "dataContent2",
    "title2",
    "text",
    "chevronRight2"
  ],
  dataContent2: ["dataContent2", "title2", "text"],
  title2: ["title2"],
  text: ["text"],
  chevronRight2: ["chevronRight2"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  property1Default: "div";
  dataContent: "div";
  title: "div";
  subtitle: "div";
  chevronRight: "div";
  property1Hover: "div";
  dataContent2: "div";
  title2: "div";
  text: "div";
  chevronRight2: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenuItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMenuItem__VariantsArgs;
    args?: PlasmicMenuItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMenuItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMenuItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMenuItem__ArgProps,
          internalVariantPropNames: PlasmicMenuItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMenuItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "property1Default") {
    func.displayName = "PlasmicMenuItem";
  } else {
    func.displayName = `PlasmicMenuItem.${nodeName}`;
  }
  return func;
}

export const PlasmicMenuItem = Object.assign(
  // Top-level PlasmicMenuItem renders the root element
  makeNodeComponent("property1Default"),
  {
    // Helper components rendering sub-elements
    dataContent: makeNodeComponent("dataContent"),
    title: makeNodeComponent("title"),
    subtitle: makeNodeComponent("subtitle"),
    chevronRight: makeNodeComponent("chevronRight"),
    property1Hover: makeNodeComponent("property1Hover"),
    dataContent2: makeNodeComponent("dataContent2"),
    title2: makeNodeComponent("title2"),
    text: makeNodeComponent("text"),
    chevronRight2: makeNodeComponent("chevronRight2"),

    // Metadata about props expected for PlasmicMenuItem
    internalVariantProps: PlasmicMenuItem__VariantProps,
    internalArgProps: PlasmicMenuItem__ArgProps
  }
);

export default PlasmicMenuItem;
/* prettier-ignore-end */
