/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: ZLmp4hDUFHgw

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicHeadRightModal.module.css"; // plasmic-import: ZLmp4hDUFHgw/css

import ArrowExpandIcon from "./icons/PlasmicIcon__ArrowExpand"; // plasmic-import: 4Uzo9N5hFxaQ/icon
import MenuCloseMdIcon from "../blank_project/icons/PlasmicIcon__MenuCloseMd"; // plasmic-import: ov_pm5ZDY9Dq/icon

createPlasmicElementProxy;

export type PlasmicHeadRightModal__VariantMembers = {
  opened: "opened";
};
export type PlasmicHeadRightModal__VariantsArgs = {
  opened?: SingleBooleanChoiceArg<"opened">;
};
type VariantPropType = keyof PlasmicHeadRightModal__VariantsArgs;
export const PlasmicHeadRightModal__VariantProps = new Array<VariantPropType>(
  "opened"
);

export type PlasmicHeadRightModal__ArgsType = {};
type ArgPropType = keyof PlasmicHeadRightModal__ArgsType;
export const PlasmicHeadRightModal__ArgProps = new Array<ArgPropType>();

export type PlasmicHeadRightModal__OverridesType = {
  headRightModal?: Flex__<"div">;
  wraper?: Flex__<"div">;
  button?: Flex__<"div">;
  area?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  expand?: Flex__<"div">;
  svg?: Flex__<"svg">;
  buttonText?: Flex__<"div">;
  counerBlock?: Flex__<"div">;
  text?: Flex__<"div">;
};

export interface DefaultHeadRightModalProps {
  opened?: SingleBooleanChoiceArg<"opened">;
  className?: string;
}

const $$ = {};

function PlasmicHeadRightModal__RenderFunc(props: {
  variants: PlasmicHeadRightModal__VariantsArgs;
  args: PlasmicHeadRightModal__ArgsType;
  overrides: PlasmicHeadRightModal__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "opened",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.opened
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"headRightModal"}
      data-plasmic-override={overrides.headRightModal}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.headRightModal,
        { [sty.headRightModalopened]: hasVariant($state, "opened", "opened") }
      )}
    >
      <div
        data-plasmic-name={"wraper"}
        data-plasmic-override={overrides.wraper}
        className={classNames(projectcss.all, sty.wraper, {
          [sty.wraperopened]: hasVariant($state, "opened", "opened")
        })}
      >
        <div
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames(projectcss.all, sty.button, {
            [sty.buttonopened]: hasVariant($state, "opened", "opened")
          })}
        >
          <div
            data-plasmic-name={"area"}
            data-plasmic-override={overrides.area}
            className={classNames(projectcss.all, sty.area, {
              [sty.areaopened]: hasVariant($state, "opened", "opened")
            })}
          >
            <div
              data-plasmic-name={"freeBox"}
              data-plasmic-override={overrides.freeBox}
              className={classNames(projectcss.all, sty.freeBox, {
                [sty.freeBoxopened]: hasVariant($state, "opened", "opened")
              })}
            >
              <div
                data-plasmic-name={"expand"}
                data-plasmic-override={overrides.expand}
                className={classNames(projectcss.all, sty.expand, {
                  [sty.expandopened]: hasVariant($state, "opened", "opened")
                })}
              >
                <PlasmicIcon__
                  data-plasmic-name={"svg"}
                  data-plasmic-override={overrides.svg}
                  PlasmicIconType={
                    hasVariant($state, "opened", "opened")
                      ? MenuCloseMdIcon
                      : ArrowExpandIcon
                  }
                  className={classNames(projectcss.all, sty.svg, {
                    [sty.svgopened]: hasVariant($state, "opened", "opened")
                  })}
                  role={"img"}
                />
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"buttonText"}
            data-plasmic-override={overrides.buttonText}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.buttonText,
              { [sty.buttonTextopened]: hasVariant($state, "opened", "opened") }
            )}
          >
            {hasVariant($state, "opened", "opened")
              ? "\u0417\u0430\u043a\u0440\u044b\u0442\u044c \u0434\u0438\u043d\u0430\u043c\u0438\u043a\u0443"
              : "\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0434\u0438\u043d\u0430\u043c\u0438\u043a\u0443"}
          </div>
        </div>
        <div
          data-plasmic-name={"counerBlock"}
          data-plasmic-override={overrides.counerBlock}
          className={classNames(projectcss.all, sty.counerBlock, {
            [sty.counerBlockopened]: hasVariant($state, "opened", "opened")
          })}
        >
          <div
            data-plasmic-name={"text"}
            data-plasmic-override={overrides.text}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text
            )}
          >
            {"\u0412\u044b\u0431\u0440\u0430\u043d\u043e: 0"}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  headRightModal: [
    "headRightModal",
    "wraper",
    "button",
    "area",
    "freeBox",
    "expand",
    "svg",
    "buttonText",
    "counerBlock",
    "text"
  ],
  wraper: [
    "wraper",
    "button",
    "area",
    "freeBox",
    "expand",
    "svg",
    "buttonText",
    "counerBlock",
    "text"
  ],
  button: ["button", "area", "freeBox", "expand", "svg", "buttonText"],
  area: ["area", "freeBox", "expand", "svg"],
  freeBox: ["freeBox", "expand", "svg"],
  expand: ["expand", "svg"],
  svg: ["svg"],
  buttonText: ["buttonText"],
  counerBlock: ["counerBlock", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  headRightModal: "div";
  wraper: "div";
  button: "div";
  area: "div";
  freeBox: "div";
  expand: "div";
  svg: "svg";
  buttonText: "div";
  counerBlock: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeadRightModal__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeadRightModal__VariantsArgs;
    args?: PlasmicHeadRightModal__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHeadRightModal__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHeadRightModal__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHeadRightModal__ArgProps,
          internalVariantPropNames: PlasmicHeadRightModal__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHeadRightModal__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "headRightModal") {
    func.displayName = "PlasmicHeadRightModal";
  } else {
    func.displayName = `PlasmicHeadRightModal.${nodeName}`;
  }
  return func;
}

export const PlasmicHeadRightModal = Object.assign(
  // Top-level PlasmicHeadRightModal renders the root element
  makeNodeComponent("headRightModal"),
  {
    // Helper components rendering sub-elements
    wraper: makeNodeComponent("wraper"),
    button: makeNodeComponent("button"),
    area: makeNodeComponent("area"),
    freeBox: makeNodeComponent("freeBox"),
    expand: makeNodeComponent("expand"),
    svg: makeNodeComponent("svg"),
    buttonText: makeNodeComponent("buttonText"),
    counerBlock: makeNodeComponent("counerBlock"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicHeadRightModal
    internalVariantProps: PlasmicHeadRightModal__VariantProps,
    internalArgProps: PlasmicHeadRightModal__ArgProps
  }
);

export default PlasmicHeadRightModal;
/* prettier-ignore-end */
