/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5RFQEMyNFhqH4SLzFAASMM
// Component: chW5EJBrUWkw

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "../blank_project/plasmic"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectModule
import { _useStyleTokens } from "../blank_project/PlasmicStyleTokensProvider"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "../blank_project/plasmic.module.css"; // plasmic-import: 5RFQEMyNFhqH4SLzFAASMM/projectcss
import sty from "./PlasmicNewsItem.module.css"; // plasmic-import: chW5EJBrUWkw/css

createPlasmicElementProxy;

export type PlasmicNewsItem__VariantMembers = {
  active: "active";
};
export type PlasmicNewsItem__VariantsArgs = {
  active?: SingleBooleanChoiceArg<"active">;
};
type VariantPropType = keyof PlasmicNewsItem__VariantsArgs;
export const PlasmicNewsItem__VariantProps = new Array<VariantPropType>(
  "active"
);

export type PlasmicNewsItem__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};
type ArgPropType = keyof PlasmicNewsItem__ArgsType;
export const PlasmicNewsItem__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicNewsItem__OverridesType = {
  newItem?: Flex__<"div">;
  title?: Flex__<"div">;
  detail?: Flex__<"div">;
  text?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  button?: Flex__<"div">;
};

export interface DefaultNewsItemProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  active?: SingleBooleanChoiceArg<"active">;
  className?: string;
}

const $$ = {};

function PlasmicNewsItem__RenderFunc(props: {
  variants: PlasmicNewsItem__VariantsArgs;
  args: PlasmicNewsItem__ArgsType;
  overrides: PlasmicNewsItem__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "active",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.active
      },
      {
        path: "expanded",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => false
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <div
      data-plasmic-name={"newItem"}
      data-plasmic-override={overrides.newItem}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        styleTokensClassNames,
        sty.newItem,
        { [sty.newItemactive]: hasVariant($state, "active", "active") }
      )}
    >
      <div
        data-plasmic-name={"title"}
        data-plasmic-override={overrides.title}
        className={classNames(projectcss.all, sty.title, {
          [sty.titleactive]: hasVariant($state, "active", "active")
        })}
      >
        {renderPlasmicSlot({
          defaultContents:
            "\u041e\u0441\u0442\u0440\u0430\u044f \u0441\u0435\u0440\u0434\u0435\u0447\u043d\u0430\u044f \u043d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e\u0441\u0442\u044c, \u0442\u044f\u0436\u0435\u043b\u0430\u044f \u041b\u0416\u041d, \u043f\u043e\u0441\u0442\u0438\u043d\u0444\u0430\u0440\u043a\u0442\u043d\u0430\u044f \u0438\u0448\u0435\u043c\u0438\u0447\u0435\u0441\u043a\u0430\u044f \u043a\u0430\u0440\u0434\u0438\u043e\u043c\u0438\u043e\u043f\u0430\u0442\u0438\u044f, \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u043f\u043e\u0441\u043b\u0435 \u0427\u041a\u0412 \u0438 \u0412\u0410-\u042d\u041a\u041c\u041e",
          value: args.children,
          className: classNames(sty.slotTargetChildren, {
            [sty.slotTargetChildrenactive]: hasVariant(
              $state,
              "active",
              "active"
            )
          })
        })}
      </div>
      <div
        data-plasmic-name={"detail"}
        data-plasmic-override={overrides.detail}
        className={classNames(projectcss.all, sty.detail)}
      >
        <div
          data-plasmic-name={"text"}
          data-plasmic-override={overrides.text}
          className={classNames(projectcss.all, sty.text, {
            [sty.textactive]: hasVariant($state, "active", "active")
          })}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox, {
              [sty.freeBoxactive]: hasVariant($state, "active", "active")
            })}
          >
            {renderPlasmicSlot({
              defaultContents:
                "\u041a\u0440\u0438\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435 \u043d\u0430 \u0444\u043e\u043d\u0435 \u0440\u0435\u0437\u043a\u043e\u0433\u043e \u0441\u043d\u0438\u0436\u0435\u043d\u0438\u044f \u0424\u0412 \u041b\u0416 \u0438 \u0433\u043b\u043e\u0431\u0430\u043b\u044c\u043d\u043e\u0439 \u0434\u0438\u0441\u0444\u0443\u043d\u043a\u0446\u0438\u0438 \u043f\u043e\u0441\u043b\u0435 \u044d\u043f\u0438\u0437\u043e\u0434\u0430 \u043e\u0441\u0442\u0440\u043e\u0439 \u041b\u0416\u041d. \u0412\u044b\u043f\u043e\u043b\u043d\u0435\u043d\u043e \u0427\u041a\u0412 \u0441\u043e \u0441\u0442\u0435\u043d\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u0435\u043c \u0438 \u0443\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0430 \u0412\u0410-\u042d\u041a\u041c\u041e \u043d\u0430 3 \u0434\u043d\u044f \u0434\u043b\u044f \u043f\u043e\u0434\u0434\u0435\u0440\u0436\u043a\u0438 \u0433\u0435\u043c\u043e\u0434\u0438\u043d\u0430\u043c\u0438\u043a\u0438. \u041f\u043e\u0441\u043b\u0435 \u043e\u0442\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u043a\u043e\u043d\u0442\u0443\u0440\u0430 \u0441\u043e\u0445\u0440\u0430\u043d\u044f\u0435\u0442\u0441\u044f \u0432\u044b\u0440\u0430\u0436\u0435\u043d\u043d\u0430\u044f \u0437\u0430\u0432\u0438\u0441\u0438\u043c\u043e\u0441\u0442\u044c \u043e\u0442 \u0432\u0430\u0437\u043e\u043f\u0440\u0435\u0441\u0441\u043e\u0440\u043e\u0432 (\u043d\u043e\u0440\u0430\u0434\u0440\u0435\u043d\u0430\u043b\u0438\u043d, \u0430\u0434\u0440\u0435\u043d\u0430\u043b\u0438\u043d), \u0447\u0442\u043e \u0441\u0432\u0438\u0434\u0435\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0443\u0435\u0442 \u043e \u043d\u0435\u0441\u0442\u0430\u0431\u0438\u043b\u044c\u043d\u043e\u0441\u0442\u0438 \u0438 \u0433\u043b\u0443\u0431\u043e\u043a\u043e\u0439 \u0434\u0438\u0441\u0444\u0443\u043d\u043a\u0446\u0438\u0438 \u043c\u0438\u043e\u043a\u0430\u0440\u0434\u0430.",
              value: args.slot,
              className: classNames(sty.slotTargetSlot, {
                [sty.slotTargetSlotactive]: hasVariant(
                  $state,
                  "active",
                  "active"
                )
              })
            })}
          </div>
        </div>
        <div
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames(projectcss.all, sty.button, {
            [sty.buttonactive]: hasVariant($state, "active", "active")
          })}
          onClick={async event => {
            const $steps = {};

            $steps["updateActive"] = true
              ? (() => {
                  const actionArgs = {
                    vgroup: "active",
                    operation: 2,
                    value: "active"
                  };
                  return (({ vgroup, value }) => {
                    if (typeof value === "string") {
                      value = [value];
                    }

                    const oldValue = $stateGet($state, vgroup);
                    $stateSet($state, vgroup, !oldValue);
                    return !oldValue;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateActive"] != null &&
              typeof $steps["updateActive"] === "object" &&
              typeof $steps["updateActive"].then === "function"
            ) {
              $steps["updateActive"] = await $steps["updateActive"];
            }
          }}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__saDv1
            )}
          >
            {"\u041f\u043e\u0434\u0440\u043e\u0431\u043d\u0435\u0435"}
          </div>
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  newItem: ["newItem", "title", "detail", "text", "freeBox", "button"],
  title: ["title"],
  detail: ["detail", "text", "freeBox", "button"],
  text: ["text", "freeBox"],
  freeBox: ["freeBox"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  newItem: "div";
  title: "div";
  detail: "div";
  text: "div";
  freeBox: "div";
  button: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNewsItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNewsItem__VariantsArgs;
    args?: PlasmicNewsItem__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicNewsItem__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicNewsItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNewsItem__ArgProps,
          internalVariantPropNames: PlasmicNewsItem__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNewsItem__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "newItem") {
    func.displayName = "PlasmicNewsItem";
  } else {
    func.displayName = `PlasmicNewsItem.${nodeName}`;
  }
  return func;
}

export const PlasmicNewsItem = Object.assign(
  // Top-level PlasmicNewsItem renders the root element
  makeNodeComponent("newItem"),
  {
    // Helper components rendering sub-elements
    title: makeNodeComponent("title"),
    detail: makeNodeComponent("detail"),
    text: makeNodeComponent("text"),
    freeBox: makeNodeComponent("freeBox"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicNewsItem
    internalVariantProps: PlasmicNewsItem__VariantProps,
    internalArgProps: PlasmicNewsItem__ArgProps
  }
);

export default PlasmicNewsItem;
/* prettier-ignore-end */
